### ISSUE TITLE
Admin --> Forum Ranks Button goes to home site

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1011]
![ashampoo_snap_2016 09 02_21h47m08s_016_](https://cloud.githubusercontent.com/assets/19621858/18216384/a42466da-7156-11e6-84e3-d9582cca815f.jpg)

**Comment by meangczac** [comment]
No issue with current codes. Please update your end.

**Comment by Catzenjaeger** [comment]
i dosent work. i have reload all data and upload new. forum ranks and mood dosent work all other yes
i see the prefix fr fs eg .. is this the problem? or i have to create a forum before? i have none atm

**Comment by meangczac** [comment]
your server already fixed this one.

**Comment by Catzenjaeger** [comment]
yes sorry i forget to close it. Is this fix for all available or we need none?

**Comment by meangczac** [comment]
Yep, it's fixed. Your site earlier was redirecting due to this line:

https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/forum/classes/admin/ranks.php#L37

It was "FR", and your user table have no user_rights FR. Installer don't have it too, so I punched in "F" and it works. It is a part of redundancy fix - We had Forum as "Core" in Version 7. When it becomes "Infusion", the question is why keep 4 ranks if each page one abbreviation... "FR", "F", "FM", "S7" , it's infusion, one "F" is enough for all. People defuse, end of story despite many rights. People infuse, "F" injected.

We also need to run more clean up like this in the future.

**Comment by Catzenjaeger** [comment]
i use f for submit in my figurelib and for all other things i use FI --- have this conflicts now or in future? well now i can change it fast :)

**Comment by meangczac** [comment]
Yours , use FL or FIG, up to 4 chars I think
