### ISSUE TITLE
site/maincore.php --> pathinfo() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1097]
site/maincore.php
/site/infusions/xxxxx/admin.php?aid=xxxxxx&section=xxxx_form&action=edit&xxxx_id=365
pathinfo() expects parameter 1 to be string, array given
Line: 245

Source code (Line: 235 - 255)
235     $lastvisited = Authenticate::setLastVisitCookie();
236  
237  
238     // Check file types of the uploaded file with known mime types list to prevent uploading unwanted files if enabled
239     if ($settings['mime_check'] == "1") {
240         if (isset($_FILES) && count($_FILES)) {
241             require_once INCLUDES."mimetypes_include.php";
242             $mime_types = mimeTypes();
243             foreach ($_FILES as $each) {
244                 if (isset($each['name']) && !empty($each['tmp_name'])) {
245                     $file_info = pathinfo($each['name']);
Line 245 -- 1 minute ago
pathinfo() expects parameter 1 to be string, array given
246                     $extension = $file_info['extension'];
247                     if (array_key_exists($extension, $mime_types)) {
248                         if (is_array($mime_types[$extension])) {
249                             $valid_mimetype = FALSE;
250                             foreach ($mime_types[$extension] as $each_mimetype) {
251                                 if ($each_mimetype == $each['type']) {
252                                     $valid_mimetype = TRUE;
253                                     break;
254                                 }
255                             }
256

**Comment by meangczac** [comment]
This error is when $_FILES is multiple and MIMECheck is ON, and 4 out of 10 files upload is corrupt. The above code only scans for single image upload. Did not take into account 10 image upload.

This code is from v7. So if we fix, v7 still bugged, and since the script is malfunction, a broken image out of a series of image will not be processed as Intended. v7 gallery WILL have problem since the mimecheck is default on v7 with no options to turn off.

Lets fix for 9 soon. Great find @Catzenjaeger, but do not worry, the Gallery Infusion in v9 runs on defender, with no repercussions whatsoever. But if you use Dynamics/defender legacy

```
form_fileinput(...... ['multiple'=>true]);
```

 then yes, this is to tell you that your multiple file upload will break.

**Comment by meangczac** [comment]
#1014 duplicate
