### ISSUE TITLE
Installer fails on server sql fields ( Several have the same issue )

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1167]
> Please make sure you have filled out all the MySQL connection fields" 
Here , https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38025&pid=200675#post_200675
and 
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38024&pid=200672#post_200672

> on RC 4 , installation goes very well ,

**Comment by meangczac** [comment]
Issue report & thoughts..
-----------------------------------------

It's just not intuitive enough without documentation. 
I've been testing installer at least 1 time a day. 

There are 2 installer in V9.02 now:

Version 7.02 installer to Install just v7's table which will run v9 install.php after complete:
https://github.com/php-fusion/PHP-Fusion/blob/9.02/test/install.php

And the v9 installer itself via install.php at Root.

Both works.

This week the glitch fixes was column properties, but apart from that, all fields in the new installer work. It previously had redirect issues (which I'm very sure the copy DiamonBok had). That was 2 weeks old code. The latest one had all redirection fixed.

On upgrading issues, we review case by case.  Get their particulars is needed. SQL data, web path, php version, mysql version, all need to be correctly determined to give a clear cut answer without double guessing.

If clean install, and if it doesn't work, then it is an valid issue.

Both upgrade procedure and install procedure runs the same sets of code to serve v9's base table. The installer is built on such that it loads the existing table schema, compare with our array and it will build the final sql code automatically to run. I.e. if DB_USERS exist, and only user_id column is in, the installer will auto populate user_name, user_password, user_admin_password, user_salt, user_algo, etc automatically. 

I've been very cautious on this part.. and this is the part that I can guarantee stable. After a week of fixes, and multiple of core dev working here had it working, it has no room variable errors. So, core table installation is confirm no problem. 

So the correct diagnosis is this - if the core table are faulty. 

Only 2 steps to take.

1. That user has a bad table file.  2 file defines v9's latest configurations.
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/classes/PHPFusion/Installer/Lib/Core.tables.inc
https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/classes/PHPFusion/Installer/Lib/Core.settings.inc

2. Server does not meet requirements.


Diamonbok's issue, iF white page problem, it's a redirect error. Redirect can be stopped with this line of code.
````
define('STOP_REDIRECT', true);
````

The reason why Installer is now in includes folder as a class, is because it will be the foundation of rolling out auto updates.

If we can run cron job at footer.php of all worldwide php-fusion 9 site to curl into an off grid server to check for "Folder" vs fusion_get_settings('version'); and if The first folder on our upgrade server pings back greater, to initiate httpd download, and FTP file transfer. Then, using "Upgrade Now" button asking user to click, executes the Class itself to run the auto-table building we have in their includes/

This way, we do not need to know what custom table or column exist. It automatically will build what is missing secretly. Foundation for this is rolled out already.

I've already responded in forum, and we'll see each individual's report. No worry, I'll help them to get them on their feet again - if they want to be helped.

**Comment by JoakimFalk** [comment]
I have seen twice that people whom had this issue switch to RC 4 and it works for them, meaning they know how.  so it should be something glitching there. Maybe to high PHP req on some verify function or something, thats my thoughts.

**Comment by PHPFUSION-EG** [comment]
this problem happens with me only when i try to instal V9.02

but installing Rc4 is done perfect

**Comment by PHPFusion-Ar** [comment]
this problem happens with me only when i try to instal V9.02

but installing Rc4 is done perfect

its clean install , 

server meets requirements But database , maria database

**Comment by PHPFusion-Ar** [comment]
![zkdtixx 1](https://cloud.githubusercontent.com/assets/23632509/20489714/3af1fd1a-b014-11e6-861e-955b67aa4c41.png)
![k6kvort 1](https://cloud.githubusercontent.com/assets/23632509/20489724/4382eb60-b014-11e6-998a-b3d2e52e8da6.png)

**Comment by meangczac** [comment]
Ok, there is a step I might have missed out. 

I suspect very much a bad config.php file or a blank one. Idk. Instead of doing a try again button, i'll make a room to make override if I see the problem. 

I will work on the increment now after I can replicate the problem.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/e04629488a723f192179547eb533929f30054b69

Please try. This one is more persistent than the previous version.

**Comment by meangczac** [comment]
delete your config_temp.php file if sticky errors.
