### ISSUE TITLE
Undefined variable: settings

### ISSUE THREAD

**Issue by UnrealCatze** [PHPFusion/PHPFusion#1188]
infusion.php
/site1/administration/infusions.php?aid=d9xxxxxxxxxxxxxb14
Line: 22

Severity : Run-time notices
Undefined variable: settings

 and many more lines with the same error notice

English.php
/site1/administration/infusions.php?aid=d91xxxxxxxx4 **
Line: 33

Severity : Run-time notices
Undefined variable: settings

**Comment by RobiNN1** [comment]
Where is infusion.php and English.php?

**Comment by UnrealCatze** [comment]
it comes from differernt old infusions . In my last PHPF9 version it was work ... now with the newest core files not or it brings error notices (a lot!!)

**Comment by RobiNN1** [comment]
Add this code  in infusion.php before line 22

```php
$settings = fusion_get_settings();
```

**Comment by UnrealCatze** [comment]
no now i get other errors after infuse

> infusion.php
> /site1/administration/infusions.php?aid=02exxxxxxxx89b
> Line: 23
> 
> Severity : Run-time notices
> Undefined variable: settings


> Query Error: INSERT INTO fusion62825_cookie_control (cookie_id, cookie_cookie, cookie_default, cookie_usage, cookie_desc)
> Stack Trace:
> #0 /var/www/vhosts/xxxxxxxxxxs.com/httpdocs/site1/includes/classes/PHPFusion/Database/Driver/PDOMySQL.inc(63): PDO->prepare('INSERT INTO fus...')
> #1 /var/www/vhosts/xxxxxxxxxxs.com/httpdocs/site1/includes/classes/PHPFusion/Database/AbstractDatabaseDriver.inc(300): PHPFusion\Database\Driver\PDOMySQL->_query('INSERT INTO fus...', Array)
> #2 /var/www/vhosts/xxxxxxxxxxs.com/httpdocs/site1/includes/db_handlers/all_functions_include.php(112): PHPFusion\Database\AbstractDatabaseDriver->query('INSERT INTO fus...', Array)
> #3 /var/www/vhosts/xxxxxxxxxxs.com/httpdocs/site1/includes/classes/PHPFusion/Installer/Infusion.core.inc(614): dbquery('INSERT INTO fus...')
> #4 /var/www/vhosts/xxxxxxxxxxs.com/httpdocs/site1/includes/classes/PHPFusion/Installer/Infusion.core.inc(147): PHPFusion\Installer\Infusion_Core->insertdbrow_infuse(Array)
> #5 /var/www/vhosts/xxxxxxxxxxs.com/httpdocs/site1/administration/infusions.php(26): PHPFusion\Installer\Infusion_Core->infuse('cookie_control')
> #6 {main}
> Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by meangczac** [comment]
Error Nature: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

> **The test benchmark** 
If all infusions can infuse without a problem, it has nothing wrong with the script itself so there is nothing to fix. Unless the claim is say news, gallery, downloads, faqs, weblinks, articles, blog, forum cannot be infused, then this issue is valid.

I will close because this repository has nothing to do with personal work scope.

**However, please show us the $inf_insertable[] in your infusion.php that is responsible for it. We can see and maybe help resolve it out.** 

First, copy your whole infusion.php into - http://phptester.net/ - see what it says.
