### ISSUE TITLE
Articles doesn't work

### ISSUE THREAD

**Issue by Rizado** [PHPFusion/PHPFusion#1217]
Articles are visible in Admin Panel, but they are not visible in a frontend.
DB and lagnuage are correct, locale updated too.

**Comment by Rizado** [comment]
OK, I found a problem. In previous version article_cat_status field had other value. And all categories were marked as drafts (but I added an article in one category).
Please check this because any user is not able to solve such problem.
Thanks!

**Comment by DavidGuetl** [comment]
Hey Rizado!

I can change the Standard Value of the article_cat_status. Than all Categories after a Update are marked as "non Draft (Published)". Or did you mean a other Problem? ;)

**Comment by Rizado** [comment]
See yourself. I think, in first update must be easy for users. If they have published article categories - it must leave published. And what is value for this field - it's secondary.

P.S. See locale - value repeated twice:
$locale['article_0000'] = "Articles";
$locale['article_0001'] = "Articles";
This is not error?

**Comment by Rizado** [comment]
For myself I found SELECT query and solved problem - I can change values directly in DB.

**Comment by DavidGuetl** [comment]
I understand what you mean, but i add this Field new (in Upgrade-File).
If i change there the Standard Value from "1" to "0", all Categories are published after a Update.

Locale is correct.
- article_0000 is used for Sitetitle and first Breadcrumb.
- article_0001 is used for Tab Title and second Breadcrumb.
Because in German will be 0000 -> "Artikel Datenbank" and 0001 -> "Artikel".

**Comment by Rizado** [comment]
I think that better way is to change if you don't want to have panic from users. Only small part of them will be able to fix this.

**Comment by DavidGuetl** [comment]
Ok, i upload the fix in an Hour .. only two Lines to change :-)
