### ISSUE TITLE
IDEA: Facebook login

### ISSUE THREAD

**Issue by Catzenjaeger** [PHPFusion/PHPFusion#1238]
the most new portals and websites offer a facebook login. 
It is possible to make this option in PHPF9? This would be nice and i guess for us all it brings more visitors and content

**Comment by JoakimFalk** [comment]
Social applications in general are always better to do as AddOns.
This is because of the non static nature of these things, for one they change their APIs regularly and others simply disappears from the market.
If we have like FB,Twitter,Google login etc we are forced to maintain the core pack for every change they also do.

**Comment by meangczac** [comment]
Addon.. Addon. PHP-Fusion does not rely on 3rd party Technologies. Exception is TinyMCE. 

We are the BFF with them.
