### ISSUE TITLE
Pagination on the front page

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#1285]
My 2 sites are clean install RC5
We solved at 9.01 worked MNE
https://github.com/php-fusion/PHP-Fusion/issues/812
But 9.02 is not in news.php total pagination on the front page?

Meet or, I'm sorry, I can not find, the total number of pages of news (below) are not displayed
Paging function () in news.php

Page news after desbou in news.php the code:

infusions / news / classes / news / news.php, line 174:
for pagenavigation, this site is ranked down at news.php
'News_pagination' => $ pagination // Kvido nodif.

But the news pagination whole is to create code
infusions / news / templates / news.php, line 176:

echo "</ div> \ n";

            if ($ info [ 'news_total_rows']> $ news_settings [ 'news_pagination']) {
                $ Type_start = isset ($ _ GET [ 'type'])? "Type =". $ _ GET [ 'type']. "& Amp;" : '';
                $ Cat_start = isset ($ _ GET [ 'cat_id'])? "Cat_id =". $ _ GET [ 'cat_id']. "& Amp;" : '';
                echo '<div class =' ​​text-center-t m-10 m-b-10 '> ". makepagenav ($ _ GET [' rowstart ']
                           $ News_settings [ 'news_pagination']
                           $ Info [ 'news_total_rows'], 3,
                           INFUSIONS. "News / news.php?". Cat_start $. $ Type_start). "</ Div> \ n";
            }
        } Else {
            echo '<div class =' ​​text-wellbeing center '>'. $ locale [ 'news_0005']. "</ div> \ n";
        }

        CloseTable ();

    }
}

Or lack continuity after changes in 2.9?
Thanks!

**Comment by meangczac** [comment]
Pagination on the News snippet?

**Comment by Kvido** [comment]
No, snippets!
I'm talking about pagination in the news at the list, a listing of individual cells newsletter. At the end of the list (below), page 1, page 2, page 3 .....

**Comment by FrederickChan** [comment]
Snippets wont have pagination. Only full news have pagination. 

How to resolve double pagination? Take out pagination button in news intro snippet?

Discussion needed.

**Comment by meangczac** [comment]
I make new function ... get_news_text() to handle this.

**Comment by Kvido** [comment]
I see. Nice talking to! I wish zing!

**Comment by meangczac** [comment]
Ok, for this issue, please have a look at this line:
https://github.com/php-fusion/PHP-Fusion/blob/9.02/infusions/news/classes/news/news.php#L303
The news introduction snippet pagebreak is removed over the multiple fixes which is the current best model after multiple issues takes place. I think the community best logical interpretation is that it was not making sense to have multiple introductory content into split pages. 
Page break only works now, when $_GET['readmore'] exist, as in full news item reading only.

For news, I have already divide news_news = news introduction, news_extended = news full news recent fixes.

Then for home.php, having showing more than 10-20 items per infusion does not serve the purpose of us doing the home.php in the first place. 

Since one can always cut and paste into a custom file, I can assist at best at forum with code assist.. For master distribution purposes I'm dropping this.
