### ISSUE TITLE
Album thumbs in Gallery Administration are not created if images are small

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#134]
![album-thumb-missing](https://cloud.githubusercontent.com/assets/4210004/9355321/965f0294-4678-11e5-8844-b1fb953a72b3.png)

**Comment by meangczac** [comment]
There will be no image thumbs if image is small because thumb size will be bigger than the actual image. Actual image is 1px x 1px , $gallery_settings['thumb_w'] = 400. 

When file is being uploaded, the upload_image() function checks if image is larger than thumb treshold. If larger, it will auto create the thumb. It does not create a thumb regardless of size.
As such, it is a correct behavior for thumbnail creation by the sys.

Else, it would be caught in a "chicken first or egg first" question.

The callback should always check for thumb, if no thumb.check for t2, if no t2, then go for the actual image. If the earlier gallery does not support such callback, - i'm not mistaken, even v7 don't handle this kind of situation. I will take note of this during my lap with the new recode.
