### ISSUE TITLE
On database information, pre-filled localhost field

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1386]
Idk about others. But I think it looks like as if it is typed already since it is so specific.
For a placeholder it should be Ie, Eg your localhost etc.. Now it is "localhost" so it looks completed, since that is most peoples default address.
If you do not fill this field, the installer only throws a generic error message so the less experienced will have no idea whats going on.

**Comment by meangczac** [comment]
![installer-database](https://cloud.githubusercontent.com/assets/4078041/23289893/d7fed62e-fa87-11e6-8937-dca5c3d72daf.png)

Look at Kentico CMS installer have a test connection button. I will clear them default fill. The error message will show u why cant proceed. I will run the layers of test the connection diagnostics.

Just showing example.

**Comment by meangczac** [comment]
I just checked on new installation. There are no localhost filled. Either it is your browser autofill, or you have an existing config.php

**Comment by meangczac** [comment]
![default_install](https://cloud.githubusercontent.com/assets/4078041/23295596/66f4bdf2-faac-11e6-8541-f5688a5758b2.PNG)

Default installation says Unable to Connect to MYSQL database if wrong credentials is filled. 

The texts are placeholder texts. I'll add "e.g. localhost". Let them user try localhost. if connection error, they can contact their hosting provider about it, since we're dealing with non-IT centric users.

I don't think connection test necessary after testing this step as thought earlier. We can however provide it at a later date. I'm not going to add potential issues. Interface logic is ok for me.

**Comment by JoakimFalk** [comment]
it still says localhost on your screen right there, if you fill anything but localhost I think a generic error will pop that is non specific. Depending on screens the placeholder looks pre-filled and not placeholder. 
That is what I mean with the report. We need to add text that are very specific. Like your MySQL url ( localhost ) so it never can be misstaken from pre-filled vs placeholder.
