### ISSUE TITLE
where is install.php?

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1399]
it poofed.

**Comment by karrak1** [comment]
someone has deleted :(

**Comment by JoakimFalk** [comment]
Yeah, hehe. See you found a copy. I guess it will work? Most changes are done on class I assume.
Will test in a hour or so.
https://github.com/php-fusion/PHP-Fusion/commit/3de8191233cfc25edd15abfa27c23ad30202eaac
Closing, Thank you.

**Comment by meangczac** [comment]
Must have been the .gitignore. I renamed it and didn't realize on git commit had the deletion. My bad. Thanks @karrak1

**Comment by meangczac** [comment]
Anyway the Install.php is a static file. It doesn't has any algorithm and calculations. We can always generate it using write_file function. I did it like this because we can create and drop that file easily should upgrade is necessary. I have no method at this moment, but remote upgrade could be possible with further research.
