### ISSUE TITLE
Selected locale resets on admin access

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1411]
> I have in the Admin Panel / Settings / Language Settings - established Site locale: Russian. However the default site opens in the English language. I use Bootstrap theme, but in this template is not working, switch languages in the header. I uploaded a photo, for, viewing.
> And in general I have a strange behavior of the site. English language, knocks down, Russian. Automatically switches to English.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38286&pid=201520#post_201518

**Comment by meangczac** [comment]
//require __DIR__.'/includes/core_mlang_hub_include.php'; fix this issue. 

I need to check the hub for a bit before closing this one.

Ok, upon closer inspection. I came to conclusion..

// Mlang core should not alter $userdata records instead it should just set definition of Language, this way it will not interfere with 'permanent language update on user table' -- Bug #1411

// RC4 works because the home.php was the site opening page, and with luck not within the hub alteration range as it's home was home.php

// However, in RC5. the opening page was stuck and caught by the mlang hub (opening page being  a custom page) rules and overwrite $userdata before jumping to admin panel.

The solution would probably to define "LANGUAGE", "LOCALESET" instead of update userdata. This way, content language would switch automatically AND userdata will not reset.

**Comment by meangczac** [comment]
Mlang Core Fixes:
-----------------------
* It has dependencies on given a hardcoded specific url.... I'm not going to do anything about this, since it's a very very miniscule chance that if such url exist then the hub's specific rule will kick in. If infusions changes URL, the hub will break naturally. Modular driver is required for such matter. Be warned when you create your xxx infusions. **Do not use these reserved url.**

 * Removed dependencies on undeclared constant should infusions deleted from system (using DB_PREFIX, DB_NEWS, DB_ARTICLES, etc is non existent since it has been ported to Infusions.)
In RC4, Infusions were declared on core_constants_include.php which is wrong. It was fixed in RC5.

 * Removed tampering user language preference. This is due to this issue. When Mlang core switch user data to English, since Page is in English causing $userdata['user_language'] to update to English, and when subsequently going into Admin, English Admin Panel. #1411
