### ISSUE TITLE
mlang hub broken reditect to root on hotlink, weblinks

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1426]
For more info, https://github.com/php-fusion/PHP-Fusion/issues/1413

**Comment by meangczac** [comment]
Fixed.

Note:
When you use weblihnk.php?weblink_id=1 on URL bar, it will redirect on **current window.**

Clicking on the <a  href='' target='_blank'>click for open new window</a> is required.

Or we will need a JS option in redirect(); function and mod core for it.

redirect(....... $open_on_new_window = FALSE);
http://stackoverflow.com/questions/19851782/how-to-open-a-url-in-a-new-tab-using-javascript-or-jquery

Since we already have restrictions on github now, we'll not be covering them in 9.0.2
