### ISSUE TITLE
Install Error Cyrilic and Introduction.inc

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1472]
> Most likely, this error is due to the Cyrillic domain.
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38330&pid=201651#post_201651

**Comment by Rizado** [comment]
IDN is evil... But I'll test on my Cyrillic domain. I'll report some later.

**Comment by Rizado** [comment]
I don't see a problem. I installed PF9 at cyrillic domain (but in subfolder because at this domain works site), changed theme settings and added news. All works. Let this user will ask his hoster for support. Phone numbers:  +7 812 3093409, +7 495 6680752 (Saint Petersburg and Moscow phone numbers in international format)   8 800 5553409 (free line for Russia) :-) .
![pf9_idn](https://cloud.githubusercontent.com/assets/3373906/23801035/3824ba02-05b7-11e7-8514-5f6cb937bf5e.png)

**Comment by Rizado** [comment]
P.S. I saw site of this hoster... Hosting reference page icin development. No comments.
Server reference page too.

Let this user search feedbacks about hoster - he will read very many bad responses.

**Comment by JoakimFalk** [comment]
Thank you for testing it!
The user also confirmed just hours after your tests  today that it was his environment cuasing the issue. Closing issue.
