### ISSUE TITLE
Feature request  - seperatly Category Admin Area 

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#1485]
Sorry for my bad englisch. But i have think about a small think. Hat about an separat Admin Area entry for Category? Like ... create a new Category .... give a Name  and Description ... and then Checkboxes like is use for news  , downloads, Blogs usw. Checkboxes für every installed Infusion that use Categories. So we can Reduce the locale Files. I don't know how many work it is auf what you think about it. It is only an idea. 

Gratz

**Comment by meangczac** [comment]
Why the checkboxes? If you create category, all items should have full access to it. 

Is those category checkboxes a restrictions? And how can it reduce locale files? 

My first impression is that checkboxes control behaviour, not translations..?

**Comment by Der-WU** [comment]
Create Categories for all Infusuions ist okay too.
So we can execlude all categorie entrys in the Infusion locale to one file in locale/admin/categorys
Checkboxes was an idea i have seen in phpkit. 
But don´t know, is it harde to realiize?

**Comment by meangczac** [comment]
The point of infusions is that these are different. and non dependencies at all. Infusions are and will be standalone. But yes, common name can be made into global. I'll take that idea. 

But not now at this point of time. I know there are a lot of work concerning locale and translations, and translators are doing hard work (duplicates) even. It is very unfortunate, but cleaning up takes a 1-2 cycle of release. We will clean up slowly, that I promise.

But not the checkboxes. We can do it far more straightforward manner doing dedicated category page instead of a global one. Fusion Dynamics are very easy to implement to generate our programs.
