### ISSUE TITLE
Installing more than one viewpage (Nebula) ?

### ISSUE THREAD

**Issue by helmuthm** [PHPFusion/PHPFusion#1605]
Do you wish to install the default Nebula Theme Page?

this sentence meets you when you log in on your site the first time - fair enough.

if you want to run a multi language site and you accept to install Nebula, you end up with **1** viewpage.php?page_id=1 containing the language that is active when accepting the installation.

if you have 2, 3 or more languages installed they will all point at viewpage.php?page_id=1 as their linkt to 'Home', but probably none of the members who prefers a different language can understand/read it.

would it be totally impossible to let the install script for Nebula check if there are more languages to install and then also add viewpage.php?page_id=2, viewpage.php?page_id=3 and so on ...

**Comment by meangczac** [comment]
the viewpage.php?page_id=1 , 2, 3 is tied to $settings['opening_page'] and when you switch language, we essentially have 2 big problems to solve:

1. page 1 , 2, 3 -- which language is which page. Take a guess.
2. And if you can guessed correctly, the opening page keeps updating DB_SETTINGS ['opening_page'] key as default home. It will be messy as well.
3. And if I serialize the whole HTML content, it will be a big bloat.

The content is just a default for now, and a presentation of what widget does by default. Due to PHP-Fusion approved materials and context, we are not even allowing user to edit it.

My best bet is that many would have demo it and probably say "Ah. Now I delete it".  But - the effort of doing a demo page is there.
