### ISSUE TITLE
Upper center panels have problems in FusionTheme, they behave as below header panels should

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1645]
Welcome message & Forum Threads List activated  goes above all side panels ( right side ), See screenshot. Look at Bootstrap for example how it sohuld work, it sems ok.
![image](https://cloud.githubusercontent.com/assets/4210004/25069363/8d4110aa-227f-11e7-8e66-e79e3f31e81e.png)

**Comment by meangczac** [comment]
The Nebula Theme has 2 Slots for Full Width Presentation and 2 Slots for Bottom Presentation. (Both 1 custom 1 panel controlled)

It has 4 extra columns for USER1-USER4 slots for custom developer integration as well. (All 4 are custom)

Yes, it is not standardized as per 'conventional' layout like bootstrap.

Septenary LEFT AND RIGHT are on Left.

Nebula is focused to deliver maximum parallax content. That is why I did not group main content body on 3 positions. If I were to do so, there is so little ordinary user can do for parallax content.. since those are going to be 'developer only' that injects content via \ThemeCore::setParam('custom_position', $html);

So I wanted users to have 2 positions they can do at least on top part (above CONTENT) and 2 more positions they can do bottom part (below CONTENT) panel admin, and 1 extra position for developer on top and 1 extra position for developer on bottom. 

U_CENTER and AU_CENTER (Panel). + 1 custom. (Developer) = total 3
L_CENTER and LC_CENTER (panel) + 1 custom (Developer) = total 3

![parallax](https://cloud.githubusercontent.com/assets/4078041/25088151/b2a3bb86-23a6-11e7-91fa-0d7422fd9c54.PNG)

If we kill one, then the parallax content real estate of the theme is very minimal, and is same as Bootstrap.

**Comment by JoakimFalk** [comment]
I think it is the wrong way to do it, Can not the same be achived by excluding like left and right panels on  home.php?.  
This way we hard mod the expected theme functions with a custom theme were people on the other hand who can´t develop have no way to make center panels work as intended instead. Much better to teach how the system can exclude than teach how to code or simply say, take another theme :)

But if it is not an easy task to make it behave as intended , just leave it for now. but it is never good to break standards on a stock theme.

**Comment by meangczac** [comment]
````
but it is never good to break standards on a stock theme.
````
Agree on this one. Never thought of stock theme issue. All I am thinking is being just an alternative and making PF9 main site runs nicely with panels.

Ok, I'll push in new as follow;

TOP              |
CONTENT     | RIGHT
BOTTOM       |
