### ISSUE TITLE
Forum Tags is broken in SEO mode

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1720]
![image](https://cloud.githubusercontent.com/assets/4210004/25302576/1cb30c50-2741-11e7-9271-84d8b4392e48.png)

**Comment by meangczac** [comment]
This issue is caused by missing jquery.min.js in the Library.
I will need a moment to upload my entire copy of forum on the server.

I'm getting this now. The includes/ file is broken somehow.

![capture](https://cloud.githubusercontent.com/assets/4078041/25310194/99f6c6fe-2811-11e7-81bc-2aa2d48220a4.PNG)

**Comment by meangczac** [comment]
Now it is fixed.

http://next.php-fusion.co.uk/final9/forum/create-new-thread
