### ISSUE TITLE
User Group not translated in profile

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1754]
![screen](https://cloud.githubusercontent.com/assets/11664877/25394597/c59e1d88-29de-11e7-8f3e-a2cb9165ae56.png)

**Comment by karrak1** [comment]
Should we make it?
will be compatibility problems.
otherwise finished, :)
I update

**Comment by RobiNN1** [comment]
Or fix only url, because in seo is index.php?group_id=1 that is wrong. Correct is profile.php?group_id=1

**Comment by karrak1** [comment]
The name of the group does not change,
If enter a group name quantum_multilocale_fields(), it will be multilingual

**Comment by RobiNN1** [comment]
Not group name but the url is incorrect. http://pf9.dev/index.php?group_id=1 redirects to 404 error

**Comment by RobiNN1** [comment]
Problem with redirects is solved https://github.com/php-fusion/PHP-Fusion/commit/8a23da45f6317d072f484d6a7e41a8eacca5a5f3

**Comment by JoakimFalk** [comment]
nm, the translation issue is still there

**Comment by karrak1** [comment]
The name of the group does not change,
If enter a group name quantum_multilocale_fields(), it will be multilingual

**Comment by RobiNN1** [comment]
@karrak1 SEO translation. Example  /home.php to /homepage

**Comment by karrak1** [comment]
no..
Group name every languages Group 1 (This is in the database)
if translate group name, then database translate

**Comment by karrak1** [comment]
if translate group name and description, 
then user_groups database group_name and group_description == a:2:{s:9:"Hungarian";s:9:"Csoport 1";s:7:"English";s:7:"Group 1";}
and desc likewise

**Comment by meangczac** [comment]
My opinion is don't need and not to translate any name. 

What if you want to reserve group name in the group name? Those serialize is gonna be hard to compare since you need to unserialize and compare language to language. 

See this code.
````
$group_name = array(
'English' => "Facebook",
'German' => 'Facebook',
'Russian' => 'Facebook'
);

$current_site_language = LANGUAGE;
$check_exists = dbquery("SELECT ug.* FROM ".DB_USER_GROUPS." WHERE 
<?php 
// omg
unserialize(ug.group_name)[LANGUAGE] ?> !== $_POST['group_name''][LANGUAGE] 
?> ORDER BY group_name ASC");

````
See how difficult it will be. x amount of query loop will be necessary for this kind of checks if multilang.
Your expansion for user groups will be capped and it will be slow unoptimized User Group Development.

My opinion is leaning towards ... adding Multilang group_language = 'English' so it will not be seen in by any other national language.

The reason is this, 

Logically, if you have a group name called **"Большой босс"** , .... would you join?
Typically you find only Russian inside as member since everything with that group should be Russian. No other national user will go into that group naturally. So, you don't need to "advertise" that group name.

**Comment by meangczac** [comment]
I close this issue if it's translations.
