### ISSUE TITLE
RSS List does not check users rights when pulling content

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1829]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38601&pid=202779#post_202779

**Comment by Rizado** [comment]
@Domi-php , I wrote about this bug for @FrederickChan and now I repeat for you. We specify access level twice for Articles, News and weblinks - first time for category and second time for content item. I propose in first to remove access level for categories because for content items it will be more flexible. What you tell?
