### ISSUE TITLE
PHP-Fusion 9 Coding Standards Implementation

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#1852]
Many of our written Code Standards have been broken during the Development of PHP-Fusion 9,
Naturally we needed some fast progress, but the time has come to bring order to chaos.

https://www.php-fusion.co.uk/infusions/wiki/documentation.php?page=209

Still we do have some standards that are required from Addon Developers etc before approval.
It is very important that PHP-Fusion 9 also follow these set Standards. Which, BTW. non are up for change ( to limit the discussion ) 
Why not change Standards? 
Many larger Frameworks actually have these Standards but the primary reason is that we have PHP-Fusion 7.
PHP-Fusion 7 follow these Standards for most part. There are really nothing wrong with them. 
If we change Standards,  1 out of the 2 system will be breaking the Standards. 
That simply looks bad, even if we can debate that this is a tad better than that,  it is small things. 
We must have it uniform and I do think most agree it is easier to adjust 9 than 7 today!

Some want to use ?> <?php to switch for HTML readability etc,  and some want to use endif endwhile etc.
I really don´t want to go in to why anyone would like this or that. Point is, that is not in the Standards and they are set for very good reasons.

The most common misstakes I see today are termination of PHP code in middle of documents. with various openings here and there. That must stop and all occurances need to be changed to fluid PHP.
Also quite a lot of  endif, endwhile instead of }. We use braces in Standards.

![i939 cimgpsh_orig](https://user-images.githubusercontent.com/4210004/27003505-30aba1a8-4df8-11e7-925a-ad5788bbef58.png)

**Comment by RobiNN1** [comment]
Maybe add .editorconfig http://editorconfig.org/
All developers must [install](http://editorconfig.org/#download) plugin for IDE or editor (PHPStorm, Sublime Text, Notepad++ etc.) 

My config for PHP Fusion
```
# http://editorconfig.org
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
trim_trailing_whitespace = true

[*.min.*, *.svg]
insert_final_newline = false

```

**Comment by meangczac** [comment]
@RobiNN1 , go ahead and test it out.

And also one more configuration is for PHP-Storm ( I dont know what is that for other IDE is the CRLF format encoding). Explanation: https://www.owasp.org/index.php/CRLF_Injection

For Notepad++ https://stackoverflow.com/questions/133965/find-crlf-in-notepad

I'm changing every file as LF now on every file I open. Sometimes, with Git from everyone here have CRLF, so I'm changing it back to LF everytime. But It's ok, its not a big matter for me. Just saying.

However, when I upload to php-fusion.co.uk , the files get corrupted into single line everytime because FTP think that file is ASCII. Since we can only upload Binary mode in FTP to hosting servers. When it becomes ASCII, everything becomes single line.

**Comment by RobiNN1** [comment]
I have been testing this for weeks and still works very well in PHPStorm and Sublime Text 3.
All new files have LF. In existing files it automatically converts to LF, removes whitespace and converts tabs to spaces.

**Comment by meangczac** [comment]
For the ```?> and <?php ``` issue, it's not relevant in my work because 9.03 is not yet to be distributed to open public. It is very expedient for us to code as such as placeholders prior to templating. Those " and ' is very hard to check when it's in the thousands. 

Basically the convention says, don't mix HTML and PHP into one file. It's fine as long as it's not into distribution.  I'll clean up when distribution, so this issue is not relevant in development scope. 

Let me explain why escaping PHP is my habit of doing things.  See image:
![collapse](https://user-images.githubusercontent.com/4078041/27009650-1e4b6984-4ec6-11e7-9d70-8b11abd4ba6a.PNG)

The problem with full PHP is that you cannot collapse in Editor, especially PHP-Storm. It makes work very slow.  Because PHP-Storm see it as PHP as PHP and HTML as HTML. 

You are not suppose to have HTML or type a single ````<div>```` in PHP because PHP is not for ````<div>```` or ````<table>````, it is simply HTML, and hence MVC, MVT. 

If escaped PHP, the work is very easy to organize, especially in designing HTML layouts.  For development server, slower by a bit in exchange for hours of savings finding the little piece of extra " typo through all your files is a nightmare.  

That is why I always escape everything before porting. I won't change my way of doing things. I simply hate working slow.  I'm used to it by now.

**Comment by meangczac** [comment]
````
I have been testing this for weeks and still works very well in PHPStorm and Sublime Text 3.
````

@RobiNN1 , git

**Comment by meangczac** [comment]
See this round evolution of Template:

https://github.com/php-fusion/PHP-Fusion/blob/9.03/infusions/forum/templates/forum_input.php#L31-L73

You won't have ?> and <?php in final distribute.

You get this file to mod:
https://github.com/php-fusion/PHP-Fusion/blob/9.03/infusions/forum/templates/forms/bounty.html

Now all I need to do is to add a textarea box in a new forum admin section, and when you click "save" it will overwrite this file with your input.  Yes, it's HTML. See in couple of days next git update.

There are 7 steps to implement the full MVT system that has been developed since day 1 4 years ago. We're at Step 5 in Fusion 9.0 stable. I simply can't afford the time drag on. 

Forum 2.0 will get all of 7 steps implemented. Before all infusions follow steps.

**Comment by RobiNN1** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/f6fbe63cd79bb60cfb9f9cc2db9dfeaa64cd2a4b

**Comment by meangczac** [comment]
I clean up 1 function - render_forum_activity($info). 
This is the latest coding standard for all core development output. **No html is allowed** in render view.
We will develop administration section for editing template for non dev users.

**Comment by JoakimFalk** [comment]
Do not use whitespace x4 instead of tabs.

https://www.php-fusion.co.uk/infusions/wiki/documentation.php?page=209

**Whitespace for indentation**
Never use whitespace for indentation in your code, always use tabs with the exception of aligning arrays.
It results in more compact files, storing one tab character versus, say, four space characters.
