### ISSUE TITLE
Fatal error  Uncaught exception 'RuntimeException' 

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#1911]
For some reason I have in  a footer this messege:

```
Fatal error:  Uncaught exception 'RuntimeException' with message 'Unclosed string at position: 1025' in /home/kos/public_html/www/tomaszowiak.net/includes/classes/PHPFusion/Minifier.inc:475
Stack trace:
#0 /home/kos/public_html/www/tomaszowiak.net/includes/classes/PHPFusion/Minifier.inc(418): PHPFusion\Minifier-&gt;saveString()
#1 /home/kos/public_html/www/tomaszowiak.net/includes/classes/PHPFusion/Minifier.inc(158): PHPFusion\Minifier-&gt;loop()
#2 /home/kos/public_html/www/tomaszowiak.net/includes/classes/PHPFusion/Minifier.inc(100): PHPFusion\Minifier-&gt;minifyDirectToOutput('$('[data-submen...', Array)
#3 /home/kos/public_html/www/tomaszowiak.net/themes/templates/layout.php(154): PHPFusion\Minifier::minify('$('[data-submen...', Array)
#4 /home/kos/public_html/www/tomaszowiak.net/themes/templates/footer.php(37): require_once('/home/kos/publi...')
#5 /home/kos/public_html/www/tomaszowiak.net/infusions/news/panel.php(29): require_once('/home/kos/publi...')
#6 {main}
  thrown in <b>/home/kos/public_html/www/tomaszowiak.net/includes/classes/PHPFusion/Minifier.inc</b> on line <b>475</b>
```
Few scripts doesn work for me, ex. form elements (select, multiselect).. When I try do add new blog item I cant use datapicker. But when I editing existing item all its OK.

**Comment by meangczac** [comment]
That is caused by bad jquery script being executed. Do you have some sort of jquery going on anywhere? If no, I would like to request the stock url of the page that such error occurred to see where is the problem. 

And...We will need to disable fatal error on the minifier and have browser to report the errors instead. I will find a way soon. 

Regards, Frederick

**Comment by kosiorski-eu** [comment]
For example here:
https://www.tomaszowiak.net/infusions/news/panel.php?section=news_form

**Comment by meangczac** [comment]
Hi, please see this image below as I ran some debug testing on your site.

![capture](https://user-images.githubusercontent.com/4078041/33867277-9552dea8-df36-11e7-8e2d-7768d119287f.PNG)

I will try to fix the second error. But I bet the first error was caused by your faulty initialization of the google map API or typo.

Reference Git : https://github.com/php-fusion/PHP-Fusion/commit/280fb9e3036d6c2e62aed804ac3032c33ed82a1a

**Comment by kosiorski-eu** [comment]
You're right, google maps are bad, but another reason.

Please visit this page where I have another form without Google api. And the same problem still there.

https://www.tomaszowiak.net/submit.php?stype=b

I detect some way to resolve this. When I delete file input. This form works well well. Admin message from footer disappear and select form display normlaly.

Check here: 
https://streamable.com/s/qm8x1/hpopeh

In first part of video form is with fileinput and get fail.
