### ISSUE TITLE
Forum alias

### ISSUE THREAD

**Issue by RobiNN1** [PHPFusion/PHPFusion#1958]
Does not work forum alias

**Comment by meangczac** [comment]
Not yet develop.. All core infusions need to upgrade when it's there except Forum because already prepare forum alias.

The aliasing method coded by Thakur, is an additional top up over current Regex matches as a first override method. It's there but I removed the code, I want to wait until SEO engine confirmed with no problem before proceed

**Comment by RobiNN1** [comment]
SEO works good for me, but on Czech NSS (PHP 7.0.24) no https://github.com/php-fusion/PHP-Fusion/issues/1871 https://github.com/php-fusion/PHP-Fusion/issues/1954

I try use SEO on my Sitemap Generator but not work, I need all URLs convert to SEO friendly URLs.
https://github.com/RobiNN1/PHP-Fusion-Infusions/tree/master/infusions/sitemap_panel

**Comment by meangczac** [comment]
I will develop on the Alias feature on forum.
