### ISSUE TITLE
User Select Change Order

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2010]
**PHP Fusion Version**: 
Best match first not last.

![image](https://user-images.githubusercontent.com/4210004/38921662-96a9ac9a-42f6-11e8-97e8-53e41e6f8029.png)

**Comment by meangczac** [comment]
I have in fact finished my development on this area - search relevancy matching. i.e order by relevance.

Currently the code in this is order by user_name ASC. In which the results is going to be the last unless you are the first user . i.e. user_id = 1. 

All the results **Chan**o, **Chan**sen, **Chan** matches Chan - WHERE user_name LIKE ".$_REQUEST['q']."% ORDER BY user_name ASC.

Such an order by will always fall short of relevancy.

To have the best pin point precision, we need to utilize something called fulltext indexes. This, I have completed development, and has used such SQL in finding similar threads in the new main forum. 

First, user_name must add FULL TEXT.

![capture](https://user-images.githubusercontent.com/4078041/38934885-6e0138a4-434f-11e8-88f6-fe26b0ad7903.JPG)

When you do that, you will get a new indexes indicating it is a full text.
![capture2](https://user-images.githubusercontent.com/4078041/38934929-994aefaa-434f-11e8-8541-d7fd8ebf002d.JPG)

Now, we can use the this:
````
$result = dbquery(
"SELECT user_id, user_name, MATCH(user_name) AGAINST (:Q1) 'score' 
FROM ".DB_USERS." WHERE user_name LIKE :Q 
ORDER BY score DESC, user_name ASC", array(
':Q' => stripinput($_GET['search']),
':Q1' => stripinput($_GET['search']),
));
````
$data['score'] will be 0-100 on your search relevancy.  The higher the text matches in precision, and more occurrence it finds itself there, the higher the score is. So your no.1 result will become "Chan" instead of Chano, or Chansen since they rank lower in scoring.

It will do good on our search engine.

Now, let me increment our core batcher to support adding fulltext columns. I'll be right back with git to close this issue.

**Comment by meangczac** [comment]
@karrak1 Your Commit will only work on my account...

**Comment by karrak1** [comment]
Query Error: SELECT user_id, user_name, user_avatar, user_level, MATCH(user_name) AGAINST (:Q1) 'score' FROM fusion585ek_users WHERE user_status=:status AND user_name LIKE :Q AND user_id !='1' ORDER BY score DESC, user_name ASC, user_level DESC
Stack Trace: 
#0 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\Driver\PDOMySQL.inc(68): PDOStatement->execute() 
#1 C:\xampp\htdocs\fusion\includes\classes\PHPFusion\Database\AbstractDatabaseDriver.inc(312): PHPFusion\Database\Driver\PDOMySQL->_query('SELECT user_id,...', Array) 
#2 C:\xampp\htdocs\fusion\includes\db_handlers\all_functions_include.php(113): PHPFusion\Database\AbstractDatabaseDriver->query('SELECT user_id,...', Array) 
#3 C:\xampp\htdocs\fusion\includes\dynamics\assets\users\users.json.php(36): dbquery('SELECT user_id,...', Array) 
#4 {main}
Error Nature: SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list

**Comment by meangczac** [comment]
Click FULL TEXT at your user_name
