### ISSUE TITLE
A more global way to save cookies/site paths, redirs so the login does not become specific domain bound

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2053]
It would be very beneficial if we could have any domain point to anygiven Fusion installation and be able to use all services from the domain that points to the wanted installation.

I guess there could be some unwanted effects on that so perhaps a list of allowed domains to accept for logins could be made, I am not sure what is best here.

For example. 
If you login to Fusion main site via https://www.php-fusion.hosting
Your login will go but the cookies are still set for https://www.php-fusion.co.uk

Another example is webmasters that mix www.domain.tld and http://domain.tld,  they get unexpected errors since many see it as the same url, while it is a whole lot different for our sessions/cookies.

Example idea how it can be done, but perhaps a clever global class is smartest..
```

// Some function to detect current URI,

function url(){
    $pu = parse_url($_SERVER['REQUEST_URI']);
    return $pu["scheme"] . "://" . $pu["host"];
}

// The Array for allowed URI
$allowed = array("domain1.tld", "domain2.tld", "domain3.tld");

$url = url();
if(in_array($url, $allowed)) {

// Do stuff


}
```

Gonna need a global call / setting for it so it can be used in for example redirect() function calls.

**Comment by meangczac** [comment]
Last night, took me an hour to look into this issue, and I couldn't find a resolution. 

Today I attempt to try again, from scratch new. I recloned Andromeda and deleted my whole php-fusion folder. This needs to be go into documentation, so I'll start with a setup instruction on how to achieve the global env that this issue is addressing.

For setting up for this issue, we will start with configuration for the developers.

We will need 2 domain on local or online machine pointing to the same folder. /php-fusion/ 

http://www.php-fusion.co.uk ---> /php-fusion/
http://www.php-fusion.hosting --> /php-fusion/

This is my setup on XAMPP (documented).
https://gist.github.com/FrederickChan/4fd8e2cc83b70f31dc5a02df342e475a
