### ISSUE TITLE
Disable tokens by default and have a toggler in Security settings

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#2071]
As the title says..

**Comment by meangczac** [comment]
I've discussed with Falk on having this issue on Git earlier,

But after careful consideration, I think it is beter to have token system running but have the notice turned off by default for all situation. Token errors will be silent from now on since the development is pretty much done for Token. 

Doing so will not impact on PHP-Fusion 7 system because they don't use \defender::safe() checks, nor they use dbquery_insert() function. dbquery() still works on update and save even though there was actually a token error.

If we disable security token, then all system for version 9 could be impacted. We need them constantly turned on for Forum. 

Please test the incoming git and see what I suggest works or not. We'll monitor the situation, and if worse come to worse, then we will disable the tokens entirely.
