### ISSUE TITLE
Babylon/Artemis

### ISSUE THREAD

**Issue by ovasclub** [PHPFusion/PHPFusion#2173]
Babylon/Artemis
WARNING: Invalid Admin Panel Theme

**Comment by RobiNN1** [comment]
**Do not use Babylon branch!**

**Comment by ovasclub** [comment]
OK.
And what is the difference between Andromeda and Andromeda-9.0.3 ?

**Comment by RobiNN1** [comment]
It's same

**Comment by meangczac** [comment]
Reason we created Andromeda branch is because of the incorrect Andromeda-9.0.3 branch name. The version is 9.03.00 = i.e. v 9.3. But I don't want to risk any conflict **renaming** a branch, so **created** one instead with the exact copy. I urge everyone to switch your IDE to new branch ASAP. I'm going to **delete the old branch in 2 weeks.**
 
Don't use Babylon. It's for the core developers only. Partially unfinished especially the **profile**. 

I don't have time to deal with Babylon now because I'm coding on main still. The new Babylon will have new profile just like a social network. I know everyone is always eager, but everything is new, so don't touch it yet.
