### ISSUE TITLE
Auto logout after update profile

### ISSUE THREAD

**Issue by kosiorski-eu** [PHPFusion/PHPFusion#2227]
When I try to change some input values in edit_profile.php and I save it, it always log me out. 
Is it normal?

**Comment by meangczac** [comment]
No, a $_POST['logout'] is triggered.

Go to maincore.php find the $_POST['logout'] , uncomment the redirect, and put a debug_print_backtrace(); on it.
Then trace it back to the source how it happened.

Which version are you using? Modified or not?

On Jun 14 2019, at 8:12 pm, Konrad Kosiorski <notifications@github.com> wrote:
> When I try to change some input values in edit_profile.php and I save it, it always log me out.
> Is it normal?
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub (https://link.getmailspring.com/link/48CB56D1-A632-4092-B62D-2E064906585F@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fphp-fusion%2FPHP-Fusion%2Fissues%2F2227%3Femail_source%3Dnotifications%26email_token%3DAA7DTWLFJFIJHXUUUKJERCLP2ODKXA5CNFSM4HYHIYBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GZRJXPQ&recipient=cmVwbHkrQUE3RFRXT1FZR0VONERFTU1aT00yQzUzQ0RBMlhFVkJOSEhCV01LTjM0QHJlcGx5LmdpdGh1Yi5jb20%3D), or mute the thread (https://link.getmailspring.com/link/48CB56D1-A632-4092-B62D-2E064906585F@getmailspring.com/1?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA7DTWLD3VOIJXMIBRBW5RLP2ODKXANCNFSM4HYHIYBA&recipient=cmVwbHkrQUE3RFRXT1FZR0VONERFTU1aT00yQzUzQ0RBMlhFVkJOSEhCV01LTjM0QHJlcGx5LmdpdGh1Yi5jb20%3D).
>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by kosiorski-eu** [comment]
Im using lastet official version, 9.03.00

But I modifed something by myself, beacause before when I make changes in "Edit Profile" and save it, sometimes changes are concerned another users. 
ex. I changed my username with success. But afther that everyone have my username. So i decided to allow users to change only password.
Please visit: https://biznes.tomaszowiak.net/
This page is only for testing, so U can do anything. 
Register button is located on the right top side (gold).

**Comment by meangczac** [comment]
Alright, I'll go fiddle, and let you know.

**Comment by meangczac** [comment]
Ok, I have registered, and I must say wow, nice site you have going there. I can support your effort. Don't worry.

This problem.

``ex. I changed my username with success. But afther that everyone have my username. So i decided to allow users to change only password.``

The problem with this is the current user id value is 0 (not correctly called or merged). and you use that dbquery_insert() to update DB_USERS in whichever file it is.  Then it will look like this:

``` dbquery("UPDATE ".DB_USERS." user_name='value' WHERE user_id=0"); ```

It means update all. I can do something to core to strengthen the feature of dbquery_insert(). but that will be on Babylon candidate for 9.10, since we're done with Andromeda 9.0.3

I need to know where the URL on site that is causing the logout problem for you , or affecting other users as you have mentioned.

If you're editing user profile on edit_profile.php, go to this line.

https://github.com/php-fusion/PHP-Fusion/blob/Andromeda/includes/classes/PHPFusion/UserFieldsInput.inc#L707-L708

See that line does the update on user on edit profile.  What you can do is to stop it with a 4th parameter.

``` dbquery_insert(DB_USERS, $this->data, 'update', ['debug'=>TRUE]);```

It will print out the SQL statement for you that it will be executing. 

So i need to know the url which you update the user fields. Your site is heavily customized 💃

**Comment by JoakimFalk** [comment]
Yes nice site indeed. But this is only for Babylon. Please use https://www.php-fusion.co.uk/infusions/forum/?viewforum&forum_id=167 for support on mods regarding Andromeda.
