### ISSUE TITLE
Markups for Output Handler need to be inserted to default templates

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#229]
These markups have been like a open secret, they need to be maped and inserted, documented.
I will map and start injecting these once I end my test round on this revision.

**Comment by meangczac** [comment]
Weblinks do not have anything.
https://github.com/php-fusion/PHP-Fusion/blob/7.02.07/weblinks.php

**Comment by meangczac** [comment]
Blog. V7 don't have, will mimic news. 

Note: No existing Addon will support them because this does not exist. I will certainly going to find it hard to understand why a future solution to be made in the future to target default core blog template that not all theme will use. But regardless, it will be in, just in case we have a Tom.

**Comment by meangczac** [comment]
I think enough, covered all. Leave on for forum.
