### ISSUE TITLE
Remove navbar class from showSubLinks

### ISSUE THREAD

**Issue by sasha2002** [PHPFusion/PHPFusion#2381]
**Is your feature request related to a problem? Please describe.**
Can't fully customize menu

**Describe the solution you'd like**
had possibility to generate menus as i need!
On function showSubLinks line 429 on SiteLinks.php 
Replace :
$res = "<div id='".self::getMenuParam('id')."' class='navbar ".self::getMenuParam('navbar_class')."' role='navigation'>\n";
With :
$res = "<div id='".self::getMenuParam('id')."' class=' ".self::getMenuParam('navbar_class')."' role='navigation'>\n";

Please add it in next release ASAP.

**Comment by RobiNN1** [comment]
Simply override css. In styles.css add  #DefaultMenu.navbar{ your css }
Just few extra lines of css. It's not big deal..

And also this change will break many themes.
 So no. This idea is bad.

**Comment by sasha2002** [comment]
The problem is that I need to exclude it at all.
All what i can do with CSS, its done,
I will not write here if i can overwrite it. And is strange to have possibility to add custom class name but navbar is hardcoded, did you think it is normal?

**Comment by RobiNN1** [comment]
We use Bootstrap CSS framework so this class must be here. That's all. It's just CSS you can easily fix. This is not PHP problem that has no other solutuon.
And due to one person break many themes? No..

This is how it works, devs can accept your request or not.

Some of these themes was coded by me and there are themes that was not even originaly coded for Bootstrap. But I fixed em, yes with extra CSS.
https://www.php-fusion.co.uk/infusions/marketplace/?view=stores&sid=124
