### ISSUE TITLE
smiley bbcode

### ISSUE THREAD

**Issue by karrak1** [PHPFusion/PHPFusion#2393]
does not display the smiley bbcode

**Comment by meangczac** [comment]
hmm.. where in exactly? Can you see them in the shoutbox?

![image](https://user-images.githubusercontent.com/4078041/181194940-f7d6e487-28c7-4aea-aea8-ccd6ac4bae26.png)

![image](https://user-images.githubusercontent.com/4078041/181194985-f036bfc3-899c-43cb-95dc-8316e051185b.png)

**Comment by meangczac** [comment]
The CSS has been updated in default.css on your end. The theme is the default Magazine theme. Please check?

**Comment by karrak1** [comment]
yes, it's visible, it just doesn't put it in the text box.
choose a smilley to insert.
New install..

**Comment by meangczac** [comment]
Thank you for the explanation. It seems the bbcode.js did not load and therefore could not trigger any clicks for text insertion. The reason I did a separate action for smileys was because I'm about to expand the smileys with emojis for the next release. But the array pair is going to be a lot to work with..  😆
