### ISSUE TITLE
makepagenav function

### ISSUE THREAD

**Issue by MathiasHun** [PHPFusion/PHPFusion#2419]
core_functions_include.php

makepagenav function 

"First" and "Last" buttons do not work properly.
It's not pointing to the right place.

PHPFusion version: v9.10.30

**Comment by meangczac** [comment]
Any URL to test on? like news, forum url, etc. I suspect integration is wrong.

**Comment by karrak1** [comment]
the goal is to test the fix.
https://github.com/PHPFusion/PHPFusion/blob/3970d7b9df6f4fc2c849e2402cc399b721699000/includes/core_functions_include.php#L1746
and 
https://github.com/PHPFusion/PHPFusion/blob/3970d7b9df6f4fc2c849e2402cc399b721699000/includes/core_functions_include.php#L1781

**Comment by MathiasHun** [comment]
It works well with this.

**Comment by meangczac** [comment]
I have a working template version running on twig. Truth to be told here is that I'm worried twig direct integration now will push the package larger in size. Because my work now is A LOT bigger than the repository. I think it is best for us to slim down. This includes removing bootstrap altogether in the next release into a new plugin container. This way we can develop separate packages for users. Like if you want bootstrap 3 , enable bs3 plugin. We do an extra admin page to control these in system settings folder. 

Give me some time to sort this out. I'll revise and come out with the new db and modules. 

So for now let's just accept this patch in.

**Comment by meangczac** [comment]
When we did bs3 direct integration it was due to 
- community had waited 7 years to get a new version. Everything was in a rush.
- the roadmap was done without much thought the possibility that bootstrap is not compatible with their own older version? Bs5 html markup is totally off compared to bootstrap 3. I should have seen it coming with how bootstrap 3 was with bootstrap 2! It is my fault for overlooking this and I'll take up the responsibility to clean this up.
