### ISSUE TITLE
PDO Throws an exception and terminate script execution when trying to do a dbcount on a non existing object

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#266]
Fatal error: Call to a member function rowCount() on a non-object in /includes/classes/PHPFusion/Database/Driver/PDOMySQL.php on line 149

The issue can be repeated by for example defusing Forum, add the Forum Threads List Panel, and do a refresh with no forum installed.

Should we not get a notice instead of a total script halt on such issues?.

**Comment by meangczac** [comment]
non-object. Wait I try with my tiny skillset. Takàcs might be busy. I assign him first, then he check.

**Comment by rimelek** [comment]
Sorry, I didn't see this issue until now. 

@Domi-php  "Should we not get a notice instead of a total script halt on such issues?."

This is a FATAL ERROR. It means there is a bug somewhere in the script before the call of countRows(). We should not handle it in countRows() or throw a notice and continue the script. 

@hien- This https://github.com/php-fusion/PHP-Fusion/commit/672252a43d01aeba752d259d856568108fe3cf64 cannot solve the problem. You checked the result of rowCount() instead of $statement which was a "non-object".

I will check it later but I have to go to work now.

**Comment by JoakimFalk** [comment]
Sounds great, hope you have a great day !

**Comment by rimelek** [comment]
This is my solution: https://github.com/php-fusion/PHP-Fusion/commit/32dee62b09a2cf970178b3a9f2cc10b1b9ad758b

Every panel should handle if its dependency does not exist.

When the panel needs settings of an infusion, it can check the result of get_settings(). Otherwise, db_exists() can help to check if the needed table is installed.

If you think a notification message would be useful to show the administrator there is an unnecessary panel without its dependency, you can show a notification, but it needs to be in file of the panel. Just make sure you use "return" (it can be used in an included file) and not "exit"

**Comment by JoakimFalk** [comment]
But the ordinary MySql function does not terminate script for such things, it simply throws a notice, I mean it would be convenient for people to not have it all terminated as with the old function, not possible?

**Comment by rimelek** [comment]
In this case none of them terminate the script just PDO needs another syntax. This issue was the result of that fact. Usually it is much better to stop the script when you try to use the result set which does not exist due to an invalid SQL query. PDO is better in every aspect and the old mysql library has been deprecated so long. It can be supported for compatibility reason, however, I think almost nobody would notice if PDO were the only possibility.

I told you long time ago, when I started to work in this team, we should handle the errors the same way in both driver class (see the implemented SelectionException and ConnectionException) and we could throw exceptions also in other methods but making the PDO driver class more insecure throwing just a notice and continuing the script is a bad a idea.

Developers can show fancy notice after they handled the error and they sure the script can continue without any serious effect. 

So...

if we know where the bug is and we can fix it, then we should fix it.
If we know an issue is a result of an unexpected and unwanted case but we can eliminate the effects, we should do that and then we can show a message about this and recommend a solution.
If we know a bug is not so serious and it won't cause other issues, we can do nothing or show a message depending on the case.

But we always must know what and why we do. If we put a simple message into the methods of the database classes, we will not know what the issue can cause.

**Comment by JoakimFalk** [comment]
The problem here is for end-users, 
One  example would be if someone infuse something that has panels.
Once they defuse it,  these panels might not automatically get defused and the site stops working.
Just because the panels calls non-existing database.
The user will not be able to enter his Admin area to disable these panels, he must then use phpmyadmin, if he even can figure that it is the panels that cause this by him self. In worst case he must visit our main, send the question and wait for a day or two before we sorted the issue. 
We should always strive to make life easier for the ordinary user, outdated or not I like notices 100 times before script halts simply because it is user friendly for the average Joe, it is these people who most of the time will use our software.
Now idk if it is possible and if it is we should go with most user friendly mode.

**Comment by JoakimFalk** [comment]
I did some tinkering

$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
vs
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_SILENT);

If I change to silent in the procedural function, it works as I want it to do. It simply logs and throws a notice to admin only. 

When I change it in the databaseFactory, nothing changes.

**Comment by meangczac** [comment]
I also want to add this. Now I'm debugging settings_language.php. See the screen

![screen shot 2015-09-12 at 2 24 55 pm](https://cloud.githubusercontent.com/assets/4078041/9830250/13a1c130-595a-11e5-879c-62fc06053938.png)

While I know there is error, this error log show me nothing where the original source code is wrong. And the code that is wrong is in SQL driver?

**Comment by meangczac** [comment]
Another issue. 

```
$result = dbquery("INSERT INTO ".DB_SETTINGS." ...... ");
if ($result) { // this does not work
}
// Same goes with
$result = dbquery("UPDATE ".DB_SETTINGS." ...... ");
$result = dbquery("DELETE FROM ".DB_SETTINGS." ...... ");

```

**Comment by rimelek** [comment]
@Domi-php "The problem here is for end-users, "

I guess you did not understand me. I wrote about how we develop to avoid more issues, make the PHP-Fusion more secure and make end-users happier.

Let's assume you create a panel and try to update the database or show a private data to a user based on the result of another select. The table does not exists so you get nothing but you do not handle it perfectly and you change the database because $dontDoIt is null instead of true. Or you let in a user into a private area because  the tabel "only_from_ips" is accidentally removed, so you see there are no restriction and your private data becomes public.

I could tell you more examples why terminating is better than just a simple notice. It is better for anyone not just for developers. 

I know end-users are happy if they can ignore errors but they don't know the security risks.

Let's say you are careful and skilled enough to handle every case and your panel is totally secure (Nobody can be sure about it when they develop something especially for a not well-designed system).
You are only one of the developers. Anyone can make mistakes.

OK. So you are thinking about how we could handle a panel issue and let to sign in the administrator to remove the panel if its developer did not check the panel's dependencies?

I can tell you more solution:
1. use register_shutdown_function() to determine if the last error was FATAL and
   1.  show a link to a simple login page OR
   2. try to switch the site to debugger/safe mode (change a variable in a config file dynamically) and turn off each panel when $safeMode is true.
2. use more exceptions in Database classes, for example PHPFusion\Database\Exception\InvalidStatementException and we can catch this exception when we try to load a panel and we can tell the user which panel threw the exception, hide the panel and continue the script. If this issue happens out of panels, then it will stop the script until someone report it and a developer check if it can be handled the same way as panels.

If we choose the way of exceptions it will give us a real efficient tool for the future to handle everything as we want.

I don't say that we cannot show notices but I do say it is not enough and notices must not showed by the Database classes. They should be like "Black boxes" and do what they were invented to do a safe way.

PDO::ERRMODE_SILENT is less secure than PDO::ERRMODE_EXCEPTION so I say don't change it.

"If I change to silent in the procedural function"

I am not sure I understand what you mean. What is that procedural function? How did you set the mode?

In the case of this issue a wrong argument was passed. It is not related to the PDO's error mode.

**Comment by JoakimFalk** [comment]
I do think that I understand you perfectly.
You on the other hand does not want to embrace the fact that the issue I have will be a concern for end-users with these type of complete halts. 
From experience I know that it will cause some real issues for end-users that use the sites much more often than the devs. I also know that it will be much more so than any security issue I can think of by hiding some random query that does not perform. After all, how can they see anything when it is hidden and the notices are logged for Admins only?.
Your examples are constructed, I do not know of a single case were this actually happened. 
There is a reason we have db_prefixes, in some of your examples they totally cover the issue.

"I am not sure I understand what you mean. What is that procedural function?"

It is the first version of the PDO implemented , I wanted to test how it behaves if it was in the script or in the nature of the dbhandler. It proved that it can do what I need it to do.

I can stretch so far to see us having two modes, 1 developer mode and 2 production environment mode for the exceptions. Is it something that would be possible to fix with the DatabaseFactory you think?. I mean for us to have the option at least.

What I can not accept is us releasing anything that will totally turn end-users sites to a complete halt when they are fiddling with the system.

**Comment by meangczac** [comment]
Ok, in production, halt. More security. But, in development mode, log the notice. I did not find mysql driver crashing site so far.. why pdo crash? 

We had this discussion about fatal errors, not to fatal error anything if possible. 
A lot of users are inexperienced in tackling such phenomenon and may distress support forum blaming a lot of people for having that happen. For them, they lose trust immediately and jump to other OS. We do not want that.
