### ISSUE TITLE
After putting a message in Archive it can not be marked as unread.

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#271]
using the unread option, naturally.

**Comment by meangczac** [comment]
Yeah, I did comment in forum earlier. https://php-fusion.co.uk/forum/viewthread.php?thread_id=36780&pid=195956#post_195955

<blockquote>... But if you archive, you cannot unarchive. That defeats the admin feature. Email can do that, because we simply have unlimited count. But if unarchive back to inbox allows, the send checks will be exploited as well.</blockquote>

Here is the relevant line for exploit. During PM, the system checks this line before allow a message to be sent to a user. https://github.com/php-fusion/PHP-Fusion/blob/9.00/includes/classes/PHPFusion/PrivateMessages.php#L180

Once I reach 20 inbox, I will archive all my message till inbox count is 0. Then when my inbox is back to 20 again, I will archive all again. Repeat a few times, and unarchive all my message, my inbox will be greater than 20... possibly in 100. User Info Panel takes this into count.

Exploit 1: Progress bar meter.

2/(max_settings_inbox_value i.e. 20) is 2/20 and progress bar is @ 10% meter.
500/(max_settings_inbox_value i.e. 20) 2500%... 

Exploit 2: There is no need to limit inbox if we allow this to happen.. and I would have wasted last 3 days recoding the bugged calculations.

But yes, you're right, after thinking a while now, I think unarchiving can be limited to inbox max value now, since the new class function is coded, but I need to mark the new functions as stable first. Perhaps 9.1 we can extend it.

**Comment by JoakimFalk** [comment]
I see no need to make it very complicated here initially,  
The way I see it is that we have these settings, 
Inbox limit: 20, Outbox limit: 20, Archive limit: 20
If Archive is full you can´t move to it, if the Inbox is full you can´t move to it from the Archive, outbox manages it self as well by simply not increment when full.
