### ISSUE TITLE
The user field option Log User Fields was tried on website field

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#279]
It is from my understand that this would generate a entry in the user log when the option is activated and the field are changed, this did not happend. User log is empty and the field was altered a few times.

**Comment by meangczac** [comment]
My memory of the log field is to tell Admin that someone has changed their username only, or avatar, or Skype. The action for it is uncertain, thats why I left it out.

We had a discussion initiated in forum by Dan earlier telling us to change the whole locale to use gettext API for the user logging experience, hence I did not do perform any increments ( I couldn't find the forum post here.. but it's there) because I don't think it's important, clearly method was outdated and interesting subject (The urge to renew it because it's old). And I thought he's gonna do it.

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=33586&highlight=logging&pid=183272#post_183272

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=33632&highlight=user+log&pid=183485#post_183485

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=35056&highlight=gettext&pid=188838#post_188838

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=35086&highlight=gettext&pid=189040#post_189040

All these during 8.00 - and Quantum was 9.00

As codes for Quantum UF evolves, the User Log API was retrenched because it only work with the old UF model during the discussions hanging midway. Quantum did not take into account or logs any change. I almost nearly forgotten if this issue hasn't been raised. Nobody did nothing to it and we don't have time for this now.. I'm tackling far more important issues and need to make room for forum.

What i suggest is drop this feature for 9.0 - User Logging is entirely a blank page now. Keep the old method? Whats the old method? What is there to log? Store a row to SQL when User Change fields?

If I cannot complete in time, we drop user_log page from DB_ADMIN in 9.0, but keep the SQL table creation I take time to make the necessary mods and publish in 9.1. Plan B, just in case.

Talk about rescue.. :dash:

**Comment by JoakimFalk** [comment]
ok, keep old standard and we just make inserts where the current changes are, KISS style
save_user_action(action,date,?);, when the option > Log User Fields   is ticked.

**Comment by meangczac** [comment]
ok cool. I make the function then.

**Comment by meangczac** [comment]
User logging actions are done, but core logging actions for user name change, password change, admin password change, email change.. please tell me which fields must be logged, and do we have a toggler or not?

**Comment by JoakimFalk** [comment]
We don´t have a toggler, Perhaps we should have one?
Is there not a way to simply grip all and use fields desciptions locale to log ?
Something like, field > value old > value new

**Comment by meangczac** [comment]
In v7 is, email and username. 

<strong>Username</strong> : https://github.com/php-fusion/PHP-Fusion/blob/7.02.07/includes/classes/UserFieldsInput.class.php#L192

<strong>Email</strong>: https://github.com/php-fusion/PHP-Fusion/blob/7.02.07/includes/classes/UserFieldsInput.class.php#L390

I say we keep it simple for now. And as such, I have coded it to follow. As long no bug, we can close.

The rest of the User Fields created in Admin or UF module.. have the toggler.

**Comment by JoakimFalk** [comment]
perfect solution, does what it needs to do !
