### ISSUE TITLE
Rewrites for infusions

### ISSUE THREAD

**Issue by Dahlgren** [PHPFusion/PHPFusion#383]
Currently rewrites reside inside the includes folder. Would it be possible to have each infusion declare it's own rewrites?

**Comment by JoakimFalk** [comment]
Anything is possible, the whole rewrite engine need a tad more love from us.
There are some inconsistency in the match maker, it is for example hard to run more than 1 database inclusion and as a result we are forced to have multiple files for 1 section in many scenarios.
It also have issues with capital letter re-writes, like the first in the array sequence will be parsed but not the later.
mydir.php => Mydir <Works, 
mydir_sub.php => /Mydir/subdir < does not work when arrayed it reads second argument as /mydir/subdir

If we can´t patch it up good during RC we will need to Roadmap any changes to it for 9.1.
Any working solutions / suggestions in codes are naturally very welcome.

**Comment by meangczac** [comment]
I think @Dahlgren  meant to move the includes/permalink files to infusion folder itself, or at least read from there, or maybe include the rules inside infusion.php. something like that.

For now, no need to touch anything seo yet. We will revisit this the next major. Since the whole of the permalink is boiled down to 3 things.
1. Route everything to index.php
2. Inclusion for form must be root path, not seo path. This part must be rewritten. The regex must differentiate between a link and form action path. The latter cannot be translated, since seo path now  result a 403. If form action url is seo url, what happen is When post event, the core translates seo url to path, which fetches the page that has seo url path and refetches the page which has seo url and refetches the page... ie. Process Logic in a logic to be processed. infinite loop.
3. Footer replacement. 

Im thinking to replace the core with alto router. I find that class is much more optimized and worth to tinker with some mod to fit core. We just keep the current api, shouldnt be a problem to port. All engin runs on plugins rules anway.

**Comment by Dahlgren** [comment]
Yes, that would be preferable since it would make writing infusions a lot easier

**Comment by meangczac** [comment]
Ok, I'll have it read extra there. Give me a moment, I'll start patch all existing issues now.

**Comment by meangczac** [comment]
On a second thought, no, have it done at includes folder as user fields did. No point just rewrite there and not user field, and then smileys, and bbcode as well... infusions can be having all those. Just do a readme. I don't want to cause further issues here by altering any of it now.

**Comment by Dahlgren** [comment]
$available_rewrites is still only read from INCLUDES."rewrites/". Could this be changed to also include from infusions too?

**Comment by Dahlgren** [comment]
Alright, fair point

**Comment by meangczac** [comment]
:+1:
