### ISSUE TITLE
[img] and [url] broken in forum bbcode

### ISSUE THREAD

**Issue by Dahlgren** [PHPFusion/PHPFusion#422]
Image and url links are prefix with "../"

**Comment by meangczac** [comment]
ok. will test after i sleep

**Comment by meangczac** [comment]
Let me guess, You have SEO turn on? I tried , there is a problem with token still in forum front end when I tried to post. Seems the recycler is not working when redirect to another page that contains a form. But there is no problem with url.

I will clear token another round. I thought i had it fixed, but apparently it did not.

I would appreciate if the issue is more clear or show me exactly how did the error occur.. or what url can i test with.

**Comment by meangczac** [comment]
Permalink Display class:

```
/**
     * Append the ROOT Dir Path to all relative links, which are from website
     *
     * This function will append the root directory path for all links, which
     * are in website. (Not External HTTP links)
     *
     * @access private
     */
    private function appendRootAll() {
        if (preg_match("/(href|src)='((?!(htt|ft)p(s)?:\/\/)[^\']*)'/i", $this->output)) {
            $basedir = str_replace(array(".", "/"), array("\.", "\/"), BASEDIR);
            $basedir = preg_replace("/(href|src)='(".$basedir.")*([^\']*)'/i", "$1='".ROOT."$3'", $this->output);
            // Remove ../ before http://
            $loop = 7;
            for ($i = 1; $i <= $loop; $i++) {
                $basedir = str_replace(str_repeat('../', $i).'http://', 'http://', $basedir);
            }
            // Remove ../ before https://
            for ($i = 1; $i <= $loop; $i++) {
                $basedir = str_replace(str_repeat('../', $i).'https://', 'https://', $basedir);
            }
            $this->output = $basedir;
        }
    }
```

This is the culprit. Need fixing.

**Comment by hien-** [comment]
Ok, the fix as follows in the PermalinkDisplay.php in your classes (I think .. I calculated scenario where the only difference between internal link and external link is mainly the difference of the "://" character since we want to escape anything with it.

Find this: 
````
$basedir = preg_replace("/(href|src)='(".$basedir.")*([^\']*)'/i", "$1='".ROOT."$3'", $this->output);
````
And Replace with this
````
$basedir = preg_replace("/(href|src)='(".$basedir.")*([^\'W]*)'/i", "$1='".ROOT."$3'", $this->output);
````
Adding a W apparently will only replace those links without :// (not character) 

Should fix this issue.

**Comment by meangczac** [comment]
The difference between an internal link is the character ":"

I dont see people using images:80/ or gif:image.png it will not be valid so escaping that will get rid of the external link bb code issues.

Replacing this: 

```
$basedir = preg_replace("/(href|src)='(".$basedir.")*([^\']*)'/i", "$1='".ROOT."$3'", $this->output);
```

with

```
$basedir = preg_replace("/(href|src)='(".$basedir.")*([^\':]*)'/i", "$1='".ROOT."$3'", $this->output);
```

I do not think i need to rewrite permalinksDisplay after all. It's quite steady after Rimelek touched it.
