### ISSUE TITLE
Blog adds extra quote marks to inserted images

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#442]
With TINY Enabled
both " and ' are there as seen in the screen.
![more-quotes](https://cloud.githubusercontent.com/assets/4210004/10938052/85403530-82f7-11e5-9d6c-b478758b839d.jpg)

**Comment by meangczac** [comment]
I found several problems with this, I found 6 issues relating to TinyMCE integration, and since I spend equal time on fixing all these files, I will eliminate and push in upgrades to motivate sync.

[Watch Next Upgrade](https://youtu.be/L9jzr3pKyRE)

**Comment by meangczac** [comment]
All image paths to "../../image/" will be translated to "image/" on home.php - this is verified.
All image paths are confirmed as well on blog front and blog extended , news front and news extended.

![2015-11-06_10h24_23](https://cloud.githubusercontent.com/assets/4078041/10987681/ac156214-8470-11e5-9f34-ff415e1b08d9.png)

**Comment by JoakimFalk** [comment]
Problem remains on next.

**Comment by meangczac** [comment]
The issue was --

<blockquote>With TINY Enabled
both " and ' are there as seen in the screen.</blockquote>

Not really, it's working on Tiny. I just tested. Question back now is how did you add those non-working image?

![capture](https://cloud.githubusercontent.com/assets/4078041/11031629/cabe97b0-8710-11e5-8281-8c8a8142c847.PNG)

**Comment by JoakimFalk** [comment]
Ok Tiny works, adding images with image button without Tiny does not :)

**Comment by meangczac** [comment]
2 issue here then.
1. One expects when administration used `<img src='../images/'>` means IMAGES, `<img src='images/'>` also means IMAGES; `<img src='../../../../../../../images/>` also means IMAGES. They all bear different paths in home, forum, blog, and people also expect that <u>it will work</ul> both in <u>BASEDIR."home.php"</u> <strong>and</strong> <u>INFUSIONS."xxx_infusion/xxx.php"</u>

It was not a problem if blog.php was originally BASEDIR."blog.php", but now it's in INFUSIONS."blog/blog.php"; So just to address where this issue - the image button should not be in the textarea at all since the items are going to appear both in home and infusion. We're talking about hardcoded html, not php. 

Not to mention that there there is SEO again (and for god knows how it will parse) that assumes everything is delivered at root. That's problem 1. 

It's like I type $3.00 and store into SQL and it suppose to be MYR, SGD and USD at the same time when view through different page.

Solution:

```
/**
 * Parse and force image/ to IMAGES directory
 * Neutralize all image dir levels and convert image to pf image folder
 * @param $data - text of paragraphs texts
 * @return string
 */
function parse_imageDir($data) {
    $str = str_replace("../", "", $data);
    return (string) str_replace("images/", IMAGES, $str);
}
```

Using this parse function will convert images to show on both home, infusions, and no matter how many level down your program script is. 

Next is the problem of using single quoted html code. Legit-ly speaking `<img src='...'>` is kinda wrong. It's suppose to be `<img src=\"....\">` To address the point. Is not a bug so to say, but a usage problem.

Solution: in order to achieve - there is a shorter solution. change the click button to double quote when you click the html img button. But again, it could screw single quotes. So another solution is to use ENT_QUOTES utf-8, as the stock one only deals with double quotes, that is why single quoted <img src=''> does not work. 

I will git in for blog, if all ok, all infusions will change following this. 

So should be solved.

**Comment by meangczac** [comment]
All-in-one function introduced and close case. Now everything should work. 

If you use `<img src='../../../../../../../images/....'>` or `<img src="..//images/...">`

In admin, image folder is "../../"
In infusions class, image folder is "../../../"
In home, image folder is "/image/"

Now it doesn't matter what path you are viewing it from, whether from home, forum, or infusions tripled nested folder, these will route to IMAGES, and you will have no broken image. 

<strong>This applies to all textarea field only since someone added back an image selector in the textarea. I remembered I clearly taken it off because of the potential issues caused with untranslated path problem.</strong>

**Comment by JoakimFalk** [comment]
idk about this, does not feel right, will need to test it some, but to force all traffic to images sure does not feel right. it is way better to solve the root problem, extra quotes added. why?

**Comment by meangczac** [comment]
html_entity_decode doesn't support single quote translation by default. 
http://php.net/manual/en/function.html-entity-decode.php

**Comment by meangczac** [comment]
I'm not sure if we can use bracketed {IMAGES} tag for the translation in text fields to specify that must be image folder. 

```
<img src='{IMAGES}logo.png'>
```
