### ISSUE TITLE
space in comments in Septenary theme

### ISSUE THREAD

**Issue by LynX88** [PHPFusion/PHPFusion#457]
Hello, thank you very much for developing new version of Php-Fusion. I love this system since i started my first cms website powered by Php-Fusion 6.

We are planning to create sport website portal and we want use your new version of PF.

We will help with reporting bugs, deficiencies, etc. 

For example, mayber bigger space between comments in Septenary´s theme:

![space_theme](https://cloud.githubusercontent.com/assets/2040931/11127897/e08ed4a2-8976-11e5-94f2-17be8222d7c7.jpg)

**Comment by meangczac** [comment]
Hi, thank you for interest in the project and continuing your support. All help is appreciated. 
I'm the lead developer and I'll be assisting mainly on the debugging process. Please reset assured if there are any request and issues (not modifications), the developer team and I will be able to cater for it.

In 9, we keep maximum of 3 css files work together. 
1. We use a default.css in templates folder to ensure backwards compatibality for version 7 theme.
2. The bootstrap css file if you turn on bootstrap to support anything lacking which bootstrap required.
3. If you customized your theme, the bootstrap css file will not be used and will be merged with your theme settings using our new internal LESS parser.

Templates . Each part runs its own HTML templates through functions. The concept is to replace the entire site make up with ideas behind render_news() which has been already done since version 6. Now, even the forum runs on render_ something function. They are available as stock default in each /templates/ folder in infusions respectively. To override these, you need to copy the same codes into your theme, and include the declaration before render_page() function.
