### ISSUE TITLE
SEO replace & with &amp; in places where it should not

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#496]
One example, but there are also other places where it is more problematic. Last fix to this issue broke the BBCode bars. The fix to BBCode bars brought back this issue. Let´s avoid it next round.
![untitled-2](https://cloud.githubusercontent.com/assets/4210004/11437086/0db9f0a4-94eb-11e5-980a-0e84ed4a5871.jpg)

**Comment by JoakimFalk** [comment]
Extra note, the replacements also breaks all links to admin for example direct edit for blog, article, news etc.

**Comment by JoakimFalk** [comment]
It also affect all types of pagination, so can not test it propperly.

**Comment by JoakimFalk** [comment]
Most of the forum is non operational due to this atm.

**Comment by meangczac** [comment]
&amp contains &, so &amp; becomes &amp+amp; after replacement.

Meanwhile, PHP build_query processing clearly recognize & only, and do not like the escaped version of &amp; I had big problem trying to solve this in clean_request() as well, because it is not read by the router. As a result, lang switch broken.

There... my guess is correct

http://next.php-fusion.co.uk/RC7/blogs/1/test-blog-%C3%A5-%C3%A4-%C3%B6-and-test-and-amp;

Anyway, I took out the &nbsp; for Blog Archive Panel and use some HTML codes as replacement.

In addition, I'll add 2 more functions into the class so you can test it easier.

**Comment by meangczac** [comment]
Just look into html_in and html_out function. Play with em and see what is the configuration needed. 

What I know so far is ordinary &amp; must show as & when HTML renders. 

I have reset some after testing the input, and output i put blank. When i try decode output, SEO don't get translated.

**Comment by meangczac** [comment]
should fix by now.
