### ISSUE TITLE
Random notice in the SEO Engine 

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#537]
Rewrite/RewriteDriver.php Undefined index: 0  Line: 507

This one comes in PM, News, Front.

**Comment by meangczac** [comment]
Well, this is because data not returning properly. It's like dbrows() returning error if dbquery(broken_statement). So it's not good to write a fix on dbrows() or else you will not know your broken statement is in fact broken. If I fix, we will never find out broken statement.. which is bad. 
Message was broken earlier, so this is normal. 

We could have an ini_set('display_errors', 'Off'); in SEO engine should we want better UX against bad drivers.
