### ISSUE TITLE
token is invalid upon password reset from admin notice

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#555]
I got the error in the system log after reseting admin password.

**Comment by meangczac** [comment]
For me it's a mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set()
Line: 652 - I can't test.

But yes, A token can only be used once. If you post, you need to refresh to get new token because old token is used and trashed. 

I adjust to refresh no matter what. See commit.
