### ISSUE TITLE
After editing a theme preset and saving the current preset automatically unloads

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#562]
You are forced to manually load it again before testing.
Loaded preset should stay loaded.

![untitled-10](https://cloud.githubusercontent.com/assets/4210004/11739902/1f937b38-9fef-11e5-8391-02bb3a0f49e8.jpg)

**Comment by meangczac** [comment]
I did not set it active because.. If site uses Septenary, admin went edit Gillette. When save, Gillette will be all over front page. If Admin save 3 themes, user of the site with default theme settings will keep looking at themes changing. Refresh, Septenary, Click forum, Gillette suddenly.  

 I can't think right or wrong now. I'm mentally too tired. I'll just fix and drop out as many issues as I can.

**Comment by hien-** [comment]
But if you think ok, then it's ok. I can't think right or wrong now. I'll just fix and drop out as many issues as possible.

**Comment by meangczac** [comment]
Will keep this as open so you will be able to consider. If ok, then we can close it.

**Comment by JoakimFalk** [comment]
I think we mix the parameters here.
1, is active theme
2, is active customization

If you edit an active theme with a loaded customization it automatically unloads this customization.
In essence the theme already does what you tried to avoid in the first place since the old layout comes back upon save without Admin intervention to load it back.

What I was looking for was simply a retain of loaded css in the theme you edit if loaded.
