### ISSUE TITLE
language switcher droplist behaves strange all the sudden

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#564]
In FireFox you need to click on it to show content, in Chrome you see content without clicking but in order to select a new lang you need to click on it before moving down the list with pointer.
![untitled-5](https://cloud.githubusercontent.com/assets/4210004/11740573/ac75ea64-9ff3-11e5-831f-c912155e1814.jpg)

**Comment by meangczac** [comment]
I'll turn off all cache and then test again later.

**Comment by meangczac** [comment]
Bro it's ok for me. Both FF and Chrome. Cache issue your end.

I dropped Smartmenus since it keeps giving me prototype console error, and sometimes failed to activate when there are multiple menus around. I added replacement in default.css to have it dropdown when hovered. 

You need to sync default.css and theme_functions_include.php, septenary header.

**Comment by JoakimFalk** [comment]
I tripple synced and have same issue on two places. 
The menu comes out but requires a physical click before I can select an option else it poofs.
It is the same with the drop down menu in the Administration. It shows content on hover but when you move mouse to an item it poofs, you need to click before.

**Comment by JoakimFalk** [comment]
It got worse with latest Git here, simply not operational.

**Comment by meangczac** [comment]
I tested with FF and Chrome on Next. The problem still exist your end? I'm talking about Septenary Theme.

OK, nevermind, lets click to show dropdown. If people want to mod, they mod it later.

**Comment by hien-** [comment]
If not solved still, i'd remove the toggle hover. Everyone click to show dropdown.
