### ISSUE TITLE
Site links form poof when trying to add links

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#582]
the creation of Site Links in the backend. If you want to add a Site Link, no form is displayed for it. It appears only a few seconds and then it disappears.

By Alex L

**Comment by JoakimFalk** [comment]
Problem remains with new CSS.

**Comment by meangczac** [comment]
```
/*
li.dropdown:hover > .dropdown-menu, li.dropdown:focus > .dropdown-menu {
    display: block;
}
*/
```

was commented out last fix?

**Comment by meangczac** [comment]
using this in theme_functions_include.php. The version of smart menus from stack overflow link i gave you earlier.

```
        /** Smart Menus */
        add_to_jquery("
        $('li.dropdown').hover(
        function(e) {
        $(this).addClass('open');
        },
        function(e) {
        $(this).removeClass('open');
        }
        );
        ");
```

**Comment by meangczac** [comment]
or else, just use click back to default bootstrap, don't hover show

**Comment by JoakimFalk** [comment]
Can still not edit links

**Comment by ghost** [comment]
Hello developers,

in my case it is the following now. I see the form for adding sitelinks and there can submit it. But when I added a SiteLink, nothing appears in the Sitelinks. I have tried it several times and just now I downloaded the latest version of PF from GitHub down.

Is it because of my system, the PF or is there still a mistake? Thank you in advance.

**Comment by meangczac** [comment]
I'll fix in a short while. Apologize about the delay.
