### ISSUE TITLE
panels are missing

### ISSUE THREAD

**Issue by Der-WU** [PHPFusion/PHPFusion#587]
after a clean install there are no panels on frontpage.

**Comment by meangczac** [comment]
SEO is on or off

**Comment by JoakimFalk** [comment]
It does state clean install. I have only done re-installs. Looked at the filters for enabled languages, it have changed so perhaps the issue is in there. New function makes less sense to me.

**Comment by Der-WU** [comment]
Don´t know SEO is on or off. Where to finde it?

**Comment by JoakimFalk** [comment]
It is off per default on a clean install don´t worry about it. You find it under system admin > Permalinks

**Comment by JoakimFalk** [comment]
I had indications on this a week ago here : https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37057
The solution for you is also in that thread, the problem is most likley here in the installer, : ".implode('.', filter_input(INPUT_POST, 'enabled_languages', FILTER_DEFAULT, FILTER_REQUIRE_ARRAY) ? : array())."
None of the statements say anything to me nor where it pulls enabled_languages from. 
So I wait for a fix that fits the new method.

**Comment by Der-WU** [comment]
Okay .

But when i enable a language on the panel an save it i become an error:

There was an error while processing your request
There must be at least a section in the filter list to use the filter

**Comment by meangczac** [comment]
Panel Type . Please select - "Display on all pages"

**Comment by meangczac** [comment]
I tested - you must have forgotten to check the language checkbox. The dump is ok with filter_input
Now, i force English mode if nothing is checked.
