### ISSUE TITLE
user fields not displaying message(?)

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#615]
Profile editing If the error-text is set, sending the incorrect profile and will not send a message unless it is set in the global.php.
Only a red dot appears on the incorrectly filled out the profiles.

Sorry this is not the fault of user_fields, but the includes / dynamics / includes / form _ *. php all occurs.
sorry google translate :(

//karrak

**Comment by meangczac** [comment]
# Documentation for Dynamics.

Each Dynamics component have default error text set to it.  It's either one of the following:

<ul>
<li>Please fill in this field</li>
<li>Please tick this checkbox</li>
<li>Please select a valid file</li>
</ul>

These error will be shown when a minimum check fails. Check can be any kind depending on the configuration of the field.

In order to replace the default error text, you add $options['error_text'] when setting up your field.

```
$options = array("error_text" => "Your custom error Text");

```

Or in a Multi-language design

```
English/locale.php
$locale['custom_error'] = "Your custom error text";

Polish/locale.php
$locale['custom_error'] = "Your custom error text";

Malay/locale.php
$locale['custom_error'] = "Your custom error text";

include INFUSIONS."locale/".LANGUAGE."/locale.php";

$options = array("error_text" => $locale['custom_error']);

```

```
form_[field_type]((string) $input_name, (string) $label, (string) $input_value, (array) $opts);
```

[field_type]  as such example:

<ul>
<li>form_select</li> 
<li>form_text</li>
<li>form_textarea</li>
<li>form_checkbox</li>
</ul>

Do not assign a error_text key into $options if you want to run default error text

$options = array("error_text" => ""); 

This tells Dynamics that error text must be intentionally left blank. Where a blank red box is desired.

Tested with all, without problem, and will fix some HTML visual errors.

Working default errors -

![default](https://cloud.githubusercontent.com/assets/4078041/12027541/1687b992-ae03-11e5-9bcb-0137d9f5ebd2.PNG)

Customized errors:

![custom_error](https://cloud.githubusercontent.com/assets/4078041/12027564/54752b86-ae03-11e5-8e79-084952219d5f.PNG)

Tested with Quantum User Fields Administration, added required. add error text. Go edit profile, submit blank. Go edit profile, removed error text. Default error showed.
