### ISSUE TITLE
Own panels are not visible

### ISSUE THREAD

**Issue by LynX88** [PHPFusion/PHPFusion#619]
When i want to add a own panel. In administration is visible (preview). Added in list of panels. With language English. Maybe issue.

**Comment by meangczac** [comment]
Sorry, but can you describe in more detail? maybe try..
1. click this and that
2. click this and that
3. do this
4. problem.

**Comment by JoakimFalk** [comment]
I have tested panels again, I noticed no issues when trying several variations.

Did you remember to activate the panel after adding it?
After adding a panel, click on the name, there are a Droplist there and you should select Enable before it goes live.

**Comment by LynX88** [comment]
Oh, sorry. Panel was disable. But name of panel in not visible.
![panel](https://cloud.githubusercontent.com/assets/2040931/12038497/e7f9238a-ae58-11e5-9228-cdf179aff10f.jpg)

**Comment by meangczac** [comment]
Bros, please check the code in V7.02.07 latest stable panel code:

https://github.com/php-fusion/PHP-Fusion/blob/7.02.07/themes/templates/panels.php#L74

V9 increments panels by allowing direct typing without using executable codes. So in panel content you can type plain text and save and it works. This is specifically designed for ordinary non-coding users and manual security risk prevention.

Rogue administrator happens. This is what we call manual security risks. Please read more about it here: http://www.infoworld.com/article/2614271/security/too-many-admins-spoil-your-security.html

We have these settings is because panel was a manual security risk for larger admin pool management. We simply make things possible for all situation depending on requirements.

If you are using the site your own only and few vetted and trusted people. You can go back to the advanced usage as per Version 7 by allowing turning on <strong>Allow PHP Execution at Admin > Settings > Security</strong> page.

Then after turning on, you can do this in panel content.

```
openside("My Panel Title");
echo "my content and all un-intended script execution like..";

// do everything
dbquery();

closeside();
```

As for why panel title was not incremented in, is because at first step introduction, the Developers did not want to break all V7 themes when used in a V9. 

Maybe we'll look into it more when we extend it in the future, but that's for later to do.

**Comment by LynX88** [comment]
Thank you very much for this information.

**Comment by meangczac** [comment]
Not at all. :smile:
