### ISSUE TITLE
Possible article rendering issues with code tags

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#644]
We could need an option in Articles and for News & Blog to disable smileys?
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37084&pid=196890#post_196890

**Comment by meangczac** [comment]
Was bbcode due to security, but it was concluded that we needed HTML more than bbcode. Besides, HTML5 supports code tag

<code>$x = $y</code> 

So no need for [code] and any smileys at all. Both submits and admin interface uses Tiny and php-fusion own HTML editor. No issue on core codes either. Reason was when bbcode was introduced first in Atom-X's theme template, News was broken, and we had problems integrating with facebook etc. Let's save us all the trouble going to troubleshoot. We got nothing to gain from this, only trouble.

I'll push it to 9.1 roadmap, as a gesture for consideration.
