### ISSUE TITLE
Any new posts that I read are not showing as 'Read' after I have viewed them. I have to log out, and back in again for them to then show up as read

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#733]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37217&pid=197438#post_197438

**Comment by iPaat** [comment]
Can someone verify that?

**Comment by Webmeteor** [comment]
My editor says that is an error in infusions/forum/viewthread.php on line 63
`$thread::increment_thread_views($info['thread']['thread_id']);`
That is not an object, thats a static method it must be
`$thread->increment_thread_views($info['thread']['thread_id']);`

possibly the method must be set to public in infusions/forum/classes/Viewthread.php on line 807

But I can't test it, because I haven't users that has posted threads in my forum.

**Comment by meangczac** [comment]
Yes, maybe static method couldn't execute twice.

**Comment by Webmeteor** [comment]
can someone test #775
maybe the issue is fixed by this patch

**Comment by JoakimFalk** [comment]
Guessing for a fix here, can´t see the issue now.
