### ISSUE TITLE
Filter error in Forum

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#859]
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37392&pid=198109#post_198109

**Comment by meangczac** [comment]
Driver/PDOMySQL.php
/infusions/forum/index.php?viewforum&forum_id=2&parent_id=1&sort=time&time=1year
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'post_datestamp' in where clause is ambiguous
Zeile: 106

**Comment by Webmeteor** [comment]
So why is all database-fields for date and time stamps in integer values and not in datetime values?
With datetime the error doesn't exists!
And we can use all mysql datetime functions for a better work with datetime values.

**Comment by meangczac** [comment]
...because the support for integral part of the design need to comply for upgrades of all php-fusion copies existed currently worldwide.

PHP-Fusion 5,6,7  needs all to be supported and upgrade could prove to be a nightmare for myself if we changed sql column type. 

time() used to be able to cope with the needs. now it comes to UNIX_TIMESTAMP(NOW()), but this issue is not about this, it's about the filter ^^;

Also I'm at the mercy of all free-to-help developers to help me out solve issues at the moment, so I can't get too deep in changes until we have more people.
