### ISSUE TITLE
Something is wrong with the visual editor when you create a blog post

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#870]
Hello Developers,

I have a problem and that if I want to create a new blog post in Admin sector, the visual editor with any written line is always bigger and bigger. So you can not work well and the editor has no fixed height as it was before.

Can you investigate further. Maybe it's with you too.

Thanks in advance. I have tested it only when you create a blog post and how it is in the news, I can not tell you.

**Comment by meangczac** [comment]
Visual editor is TinyMCE?

**Comment by ghost** [comment]
Yes!

**Comment by meangczac** [comment]
@AlexL777 , I won't git it because this is not a bug, rather a user preference, until I have the time to set a toggler for TinyMCE settings later in the settings administration, I'll teach you where and how to look to shut it down.

See this line:

https://github.com/php-fusion/PHP-Fusion/blob/9.01/infusions/blog/admin/blog.php#L277

and 

https://github.com/php-fusion/PHP-Fusion/blob/9.01/infusions/blog/admin/blog.php#L291

Replace value the autosize values from TRUE to FALSE. 

```
array("autosize"=>FALSE); // turns of autosizing on return button
array("autosize" => TRUE); // turns on autosizing on the return button
```

These are configuration parameters for the fields. 

Let me know.

**Comment by meangczac** [comment]
form_textarea() updated to allow autoresize plugin to be deactivated

**Comment by ghost** [comment]
I do not know what's going on, but I can not find this tool in the editor. How else can I set the Editor-height?

I have already the last version of this CMS downloaded from here and brought to the server. But in the admin area in PF in TinyMCE editor, I still have all the same.

I can now work only in full-screen. So you can then work well.

But with the small editor it does not work. What am I missing here?

**Comment by meangczac** [comment]
height? 

$editor_settings = array("height"=>"500px")); 

form_textarea(............ , $editor_settings);
