### ISSUE TITLE
forum_threads_list_panel shows new posts as being posted on 07/02/2106

### ISSUE THREAD

**Issue by Routhinator** [PHPFusion/PHPFusion#887]
forum_threads_list_panel shows latest forum posts as being posted on 07/02/2106, however the forum posts themselves seem to display the correct post date.

**Comment by Routhinator** [comment]
This seems to be related to the thread_lastpost value in the forum_threads table. It's abnormally high:

This is the thread_lastpost value for a new thread after upgrade:

```
4294967295
```

This is the post_datestamp of that post:

```
1460763444
```

This explains why the post itself shows the correct date but the threads panel does not.

**Comment by meangczac** [comment]
yes, again because the change was on time() on PF7 standard, but then they said time() is not compatible with Mysql for some reasons, and then suggested to NOW() and now the fix is UNIX_TIMESTAMP(NOW()) apparently on some hosting platform it was not supported somehow, which made me wondered a lot.

All updated in unison with the rest of the updates. Please check and create new issues if anything not working right again. Thank you.
