### ISSUE TITLE
All forum dates are off by 100 years and a few months since last update

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#900]
I think one date was off before patch to requested dates, now all dates are off on a 100% established host. If people use non-standard hosts and get these date issues they had previously. Change host. These type of codes seems to not be  viable for the larger public.
![laft](https://cloud.githubusercontent.com/assets/4210004/14976568/165b7392-110d-11e6-9047-8ace0fe270c5.jpg)
![forum_view](https://cloud.githubusercontent.com/assets/4210004/14976569/16711df0-110d-11e6-9ce5-cd46d9790dc8.jpg)
![forum_index](https://cloud.githubusercontent.com/assets/4210004/14976570/1683623a-110d-11e6-9770-bc05d0a12635.jpg)

https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37484&pid=198451#post_198451

**Comment by meangczac** [comment]
ok. i'll revert to time()

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/2f6d1562cebaa316981da624c1dff08645c02452

**Comment by meangczac** [comment]
Tell me **_why exactly_** again we are using NOW() or UNIX_TIMESTAMP(NOW()) ?

**Comment by Webmeteor** [comment]
The Question is why we use timestamp and not DateTime?

**Comment by JoakimFalk** [comment]
Question is, what has best general support, It would be most logical to use due to that.
Research is required, many opinions and few facts on this table now.

**Comment by JoakimFalk** [comment]
I have been reading way to long on this. 
The break down is, time(); = PHP version of Unix Timestamp. It contain all info we need.

The DATETIME type is used when you need values that contain both date and time information. MySQL retrieves and displays DATETIME values in 'YYYY-MM-DD HH:MM:SS' format. The supported range is '1000-01-01 00:00:00' to '9999-12-31 23:59:59'.

The TIMESTAMP data type has a range of '1970-01-01 00:00:01' UTC to '2038-01-09 03:14:07' UTC. It has varying properties, depending on the MySQL version and the SQL mode the server is running in.

We already store the epoch time but it is read and handled with Fusion´s own time format scripts.
https://www.php-fusion.co.uk/infusions/wiki/documentation.php?page=268

Sources : http://stackoverflow.com/questions/409286/should-i-use-field-datetime-or-timestamp

**Comment by meangczac** [comment]
For me, it was kind of backwards compatibility on upgrades, especially on the forum where upgrades could take hundreds of k records which was earlier recorded in timestamp. See the code in Version 7. 

Conversion could be a very hard thing to guarantee, for the same purpose. 

And secondly, Domi is right. We have incremented function based on datestamp. New features like the timer($timestamp) function is used in forum to calculate 'x minutes ago' is based on timestamp.  Also the native showdate() function and now in 9 upgraded to monitor day light savings.

By modding to datetime, we could land in a loop. See form_datepicker.. which runs extra code due to the birthdate user field using datetime and news, articles, weblinks entries which uses timestamp. Both runs at form_sanitizer() which needs to run many extra lines of codes which could anytime face bugs, scripts performance and use issues.

The good side is, defender supports it.. so far. It was a nightmare to code the "sensors". Downside is performance bloat. If you ask me, avoid datetime
