### ISSUE TITLE
Insert code into the News

### ISSUE THREAD

**Issue by Kvido** [PHPFusion/PHPFusion#921]
I recommend file infussions/news/admin/news.php
number 55, 61
`$news_news = "";
    if ($_POST['news_news']) {
        $news_news = str_replace("src='".str_replace("../", "", IMAGES_N), "src='".IMAGES_N, htmlspecialchars($_POST['news_news']));
        $news_news = parse_textarea($news_news);
    }`

Replace
htmlspecialchars
Reason? Unable to upload source code "pre"

**Comment by meangczac** [comment]
Ok, @Kvido , I will allow on only if you agree to turn on php_allow_exe = true . This is because not all users could agree to allow special characters enter SQL table, unless with full intention to do so. For a higher risk degree, like code eval, special chars bypass, etc.. php_allow_exe is there in Security.
