### ISSUE TITLE
User registration not working

### ISSUE THREAD

**Issue by tom-11880** [PHPFusion/PHPFusion#938]
In a fresh installation, when trying to register a new user, this error message pops up.

All registration fields had been filled correctly, so I don't understand why this comes up?

![phpfusion9-userregistration](https://cloud.githubusercontent.com/assets/20478537/16985566/9b7fe0e2-4e81-11e6-9706-e2236472a9e6.png)

**Comment by tom-11880** [comment]
Just one short note - I just checked, it works in RC3.

**Comment by JoakimFalk** [comment]
Good news ;)

**Comment by tom-11880** [comment]
Can you show me the fix, I'd like to know what the problem was?

**Comment by meangczac** [comment]
Yes, of course, the problem is here. https://github.com/php-fusion/PHP-Fusion/commit/34557d5623bb7e458331b9825a5da9d1eb7128b3

What happened was the input field that need to update an email is field name verify_password, which is blank (not rendered) in registration. I skipped that check. It's an overlook of the registration check.
