### ISSUE TITLE
List of suspected Bugs and Errors

### ISSUE THREAD

**Issue by ghost** [PHPFusion/PHPFusion#939]
**Forum**
- Options menu aint working:

It won't delete threads with edit -> delete thread
When i make a thread sticky it makes the thread locked automatic.
 Cant unlock the thread or unsticky it with edit.
When i select: disable smileys, it won't disable them
 Hide edit isn't working.
- If i move a post to a new forum it leaves on the old forum this (see attachment)

**Admin panel**
- When i delete / upload a image, it says that it can't process. But when i refresh it is uploaded / deleted.
- Can't set private message inbox/outbox/archive on zero (Unlimited).

**Comment by meangczac** [comment]
Ok, I'll look at them very soon. 

Let's take it slooooowly..... Please split them up 1 issue per problem next time too. It's very hard to keep edit and paste commits here.
- https://github.com/php-fusion/PHP-Fusion/commit/b183b2bd0eb4d566f4b4287ec8a3c0d9f7090514 It won't delete threads with edit -> delete thread
- When i make a thread sticky it makes the thread locked automatic.
  I think this one is working, I tested alright after the git change.
- https://github.com/php-fusion/PHP-Fusion/commit/96fd379fbf85458f16baa98f7ea0b59c19996de4 Cant unlock the thread or unsticky it with edit.
- https://github.com/php-fusion/PHP-Fusion/commit/d663e0b32d79f8423f8f8b4ee3218fdc3f81ef77 When i select: disable smileys, it won't disable them. 

The reason was it was read as "Enable smileys in this post" instead.. nobody saw that coming.
- https://github.com/php-fusion/PHP-Fusion/commit/481c54322c3cc60b0faae8880a54eacd37d217d7 Hide edit isn't working.
- If i move a post to a new forum it leaves on the old forum this (see attachment)
  Moving so far do not pose a problem to me. Skipping.
- https://github.com/php-fusion/PHP-Fusion/commit/9e6d1b98ddd25cc18259ac1b55dc750f208ce843 When i delete / upload a image, it says that it can't process. But when i refresh it is uploaded / deleted.
- Can't set private message inbox/outbox/archive on zero (Unlimited).
  This works on my side, you need to update dynamics and defender. file. 
  https://github.com/php-fusion/PHP-Fusion/tree/9.01/includes/dynamics
  https://github.com/php-fusion/PHP-Fusion/blob/9.01/includes/defender.inc.php
  https://github.com/php-fusion/PHP-Fusion/blob/9.01/includes/sqlhandler.inc.php

That's it.

**Comment by ghost** [comment]
Oke, I wanted to change the files but where can i find the admin, forum, post, threads folders in the classes folder? I download the PHP-Fusion 9.0 RC 3.zip files. 
So i can't find them

**Comment by meangczac** [comment]
Just replace the whole forum infusion. lol
