### ISSUE TITLE
Menu icons on left side in Admin menu are not displayed from Infusions

### ISSUE THREAD

**Issue by JoakimFalk** [PHPFusion/PHPFusion#969]
See screenshot regarding Wiki Infusion.
Image is well displayed in the Infusions list but once Infused the icon is not rendered out in the left menu.

![untitled-3](https://cloud.githubusercontent.com/assets/4210004/17832766/0bfc4134-670b-11e6-8e17-6b00dc0c5d48.jpg)

**Comment by JoakimFalk** [comment]
The issue is double confirmed on cu_db aswell.

**Comment by meangczac** [comment]
Ok, I'll have a look at it this evening.

**Comment by RobiNN1** [comment]
On my test infusion works well
![test](https://cloud.githubusercontent.com/assets/11664877/17838689/671fbca8-67d3-11e6-8155-29033cbe16c7.png)

In infusion_db.php add
`if (defined("ADMIN_PANEL")) {
    $admin->setAdminPageIcons('' ,"<i class='fa fa-YOUR-ICON fa-lg'></i>");
}`

**Comment by meangczac** [comment]
For Venus, yes. Apparently that is the case because we need an Icon in font-awesome styling. Sigh. Wait for next Update. Artemis. I drop the use of font awesome in admin links and use admin_image instead.

**Comment by JoakimFalk** [comment]
@RobiNN1 It is a very nice fix there, but we need it to be more "Global" to achive user friendlyness. Basically it is either FA / XX or use the image set else we force people to find two icons and an extra line for each Infusions they produce. I feel that it is a tad unreasonable and the most logical thing would be that the icon you select in the pack is the one that are displayed. ;)

**Comment by meangczac** [comment]
Let me explain, In SQL table DB_ADMIN:

![capture](https://cloud.githubusercontent.com/assets/4078041/18043818/d7ec64f2-6dfc-11e6-84df-46522c718d2d.JPG)

You will not see any indicator of the Icons for Core components - 

![capture2](https://cloud.githubusercontent.com/assets/4078041/18043835/fc378c56-6dfc-11e6-8427-1657a9881745.JPG)

They are from a hardcoded file - https://github.com/php-fusion/PHP-Fusion/blob/9.02/includes/classes/PHPFusion/Admin.php#L49-L106

We won't know what your image will be. i.e. 'fa fa-something' is not SQL based. It's file based.

When I styled Venus earlier on, it was short on expecting the only infusions that will ever exist is the "Shoutbox" only. I left the API there.

So the example was left there to "inject" the desired icon to aggregate the icon array manually. Hence, an API instead adding an extra column for Icons, so not to make such `requirement` on developer. It's ridiculous if it's a requirement since soon we will be out of SVG icons to use if everyone grabs one.

Instead of fixing Venus, my time was put to design the new Artemis Admin Theme. This round, no API is required. SVG entirely drop and only for core use if one needs it, they need to mod Artermis to show the SVG instead.
